#!/bin/sh
aideinit
cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
update-aide.conf
cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
mkdir /root/aide-test
touch /root/aide-test/test1
touch /root/aide-test/test2
aide -c /etc/aide/aide.conf --check
