#!/bin/sh
date=$(date -u)
if [ $(/usr/bin/id -u) -ne 0 ]; then
    echo "You must be root. This instance will be logged."
    echo "[FAIL] $USER attempted to run the search on $date." | sudo tee -a /bin/lib/sh/MK3S/logs/MK3S.log
    exit
fi
echo "---------------Games----------------|"
which 0ad && man 0ad | cat | head -n 4 | grep -i 0ad
which 0ad-data && man 0ad-data | cat | head -n 4 | grep -i 0ad-data
which 0ad-dada-common && man 0ad-data-common | cat | head -n 4 | grep -i 0ad-data-common
which 2048-at && man 2048-at | cat | head -n 4 | grep -i 2048-at
which 3dchess && man 3dchess | cat | head -n 4 | grep -i 3dchess
which 4digits && man 4digits | cat | head -n 4 | grep -i 4digits
which 7kaa && man 7kaa | cat | head -n 4 | grep -i 7kaa
which 7kaa-data && man 7kaa-data | cat | head -n 4 | grep -i 7kaa-data
which a7xpg && man a7xpg | cat | head -n 4 | grep -i a7xpg
which a7xpg-data && man a7xpg-data | cat | head -n 4 | grep -i a7xpg-data
which aajm && man aajm | cat | head -n 4 | grep -i aajm
which abe && man abe | cat | head -n 4 | grep -i abe
which abe-data && man abe-data | cat | head -n 4 | grep -i abe-data
which ace-of-penguins && man ace-of-penguins | cat | head -n 4 | grep -i ace-of-penguins
which acm && man acm | cat | head -n 4 | grep -i acm
which adanaxisgpl && man adanaxisgpl | cat | head -n 4 | grep -i adanaxisgpl
which adanaxisgpl-data && man adanaxisgpl-data | cat | head -n 4 | grep -i adanaxisgpl-data
which adonthell && man adonthell | cat | head -n 4 | grep -i adonthell
which adonthell-data && man adonthell-data  | cat | head -n 4 | grep -i adonthell-data 
which airstrike && man airstrike | cat | head -n -4 | grep -i airstrike
which airstrike-common && man airstrike-common | cat | head -n 4 | grep -i airstrike-common
which aisleriot && man aisleriot | cat | head -n 4 | grep -i aisleriot
which alex4 && man alex4 | cat | head -n 4 | grep -i alex4
which alex4-data && man alex4-data | cat | head -n 4 | grep -i alex4-data
which alien-arena && man alien-arena |cat | hean -n -4 | grep -i alien-arena
which alien-arena-data && man alien-arena-data | cat | head -n 4 | grep -i alien-arena-data
which alien-arena-server && man alien-arena-server | cat | head -n 4 | grep -i alien-arena-server
which alienblaster && man alienblaster | cat | head -n 4 | grep -i alienblaster
which alienblaster-data && man alienblaster-data | cat | head -n 4 | grep -i alienblaster-data
which amoebax && man amoebax | cat | head -n 4 | grep -i amoebax
which amoebax-data && man amoebax-data | cat | head -n 4 | grep -i amoebax-data
which amphetamine && man amphetamine | cat | head -n 4 | grep -i amphetamine
which amphetamine-data  && man amphetamine-data  | cat | head -n 4 | grep -i amphetamine-data 
which an && man an | cat | head -n 4 | grep -i an
which angband && man angband | cat | head -n 4 | grep -i angband
which angband-data && man angband-data | cat | head -n 4 | grep -i angband-data
which angrydd && man angrydd | cat | head -n 4 | grep -i angrydd
which animals && man animals | cat | head -n 4 | grep -i animals
which antigravitaattori && man antigravitaattori | cat | head -n 4 | grep -i antigravitaattori
which ardentryst && man ardentryst | cat | head -n 4 | grep -i ardentryst
which armagetronad && man armagetronad | cat | hean -n 4 | grep -i armagetronad
which armagetronad-common && man armagetronad-common | cat | head -n 4 | grep -i armagetronad-common
which armagetronad-dedicated && man armagetronad-dedicated | cat | head -n 4 | grep -i armagetronad-dedicated
which asc && man asc | cat | head -n 4 | grep -i asc
which asc-data && man asc-data | cat | head -n 4 | grep -i asc-data
which asc-music && man asc-music | cat | head -n 4 | grep -i asc-music
which asciijump && man asciijump | cat | head -n 4 | grep -i asciijump
which assaultcube && man assaultcube | cat | head -n 4 | grep -i assaultcube
which assaultcube-data && man assaultcube-data | cat | head -n 4 | grep -i assaultcube-data
which astromenace && man astromenace | cat | head -n 4 | grep -i astromenace
which astromenace-data-src && man astromenace-data-src | cat | head -n 4 | grep -i astromenace-data-src
which asylum && man asylum | cat | head -n 4 | grep -i asylum
which asylum-data && man asylum-data | cat | head -n 4 | grep -i asylum-data
which atanks && man atanks | cat | head -n 4 | grep -i atanks
which atanks-data && man atanks-data | cat | head -n 4 | grep -i atanks-data
which atom4 && man atom4 | cat | head -n 4 | grep -i atom4
which atomix && man atomix | cat | head -n 4 | grep -i atomix
which atomix-data && man atomix-data | cat | head -n 4 | grep -i atomix-data
which attal-themes-medieval && man attal-themes-medieval | cat | head -n 4 | grep -i attal-themes-medieval
which auralquiz && man auralquiz | cat | head -n 4 | grep -i auralquiz
which balder2d && man balder2d | cat | head -n 4 | grep -i balder2d
which balder2d-data && man balder2d-data | cat | head -n 4 | grep -i balder2d-data
which ballerburg && man ballerburg | cat | head -n 4 | grep -i ballerburg
which ballz && man ballz | cat | head -n 4 | grep -i ballz
which ballz-data && man ballz-data | cat | head -n 4 | grep -i ballz-data
which bambam && man bambam | cat | head -n 4 | grep -i bambam
which barrage && man barrage | cat | head -n 4 | grep -i barrage
which bastet && man bastet | cat | head -n 4 | grep -i bastet
which bb && man bb | cat | head -n 4 | grep -i bb
which beneath-a-steel-sky && man beneath-a-steel-sky | cat | head -n 4 | grep -i beneath-a-steel-sky
which berusky && man berusky | cat | head -n 4 | grep -i berusky
which berusky-data && man berusky-data | cat | head -n 4 | grep -i berusky-data
which berusky2 && man berusky2 | cat | head -n 4 | grep -i berusky2
which berusky2-data && man berusky2-data | cat | head -n 4 | grep -i berusky2-data
which between && man between | cat | head -n 4 | grep -i between
which billard-gl && man billard-gl  | cat | head -n 4 | grep -i billard-gl 
which billard-gl-data && man billard-gl-data | cat | head -n 4 | grep -i billard-gl-data
which biloba && man biloba | cat | head -n 4 | grep -i biloba
which biloba-data && man biloba-data | cat | head -n 4 | grep -i biloba-data
which biniax2 && man biniax2 | cat | head -n 4 | grep -i biniax2
which biniax2-data && man biniax2-data | cat | head -n 4 | grep -i biniax2-data
which black-box && man black-box | cat | head -n 4 | grep -i black-box
which blinken && man blinken | cat | head -n 4 | grep -i blinken 
which blobandconquer && man blobandconquer | cat | head -n 4 | grep -i blobandconquer
which blobandconquer-data && man blobandconquer-data | cat | head -n 4 | grep -i blobandconquer-data
which blobby && man blobby | cat | head -n 4 | grep -i blobby
which blobby-data && man blobby-data | cat | head -n 4 | grep -i blobby-data
which blobby-server && man blobby-server | cat | head -n 4 | grep -i blobby-server
which bloboats && man bloboats | cat | head -n 4 | grep -i bloboats
which blobwars && man blobwars | cat | head -n 4 | grep -i blobwars
which blobwars-data && man blobwars-data | cat | head -n 4 |  grep -i blobwars-data
which blockattack && man blockattack | cat | head -n 4 | grep -i blockattack
which blockout2 && man blockout2 | cat | head -n 4 | grep -i blockout2
which 3D-tetris && man 3D-tetris | cat | head -n 4 | grep -i 3D-tetris 
which Tetris\ like\ game && man Tetris\ like\ game | cat | head -n 4 | grep -i Tetris\ like\ game
which Tetris-like-game && man Tetris-like-game | cat | head -n 4 | grep -i Tetris-like-game
which blocks-of-the-undead && man blocks-of-the-undead | cat | head -n 4 | grep -i blocks-of-the-undead
which blocks-of-the-undead-data && man blocks-of-the-undead-data | cat | head -n 4 | grep -i blocks-of-the-undead-data
which bombardier && man bombardier | cat | head -n 4 | grep -i bombardier
which bomber && man bomber | cat | head -n 4 | grep -i bomber
which bomberclone && man bomberclone | cat | head -n 4 | grep -i bomberclone
which bomberclone-data && man bomberclone-data | cat | head -n 4 | grep -i bomberclone-data
which boswars && man boswars | cat | head -n 4 | grep -i boswars
which boswars-data  && man boswars-data  | cat | head -n 4 | grep -i boswars-data 
which bouncy && man bouncy | cat | head -n 4 | grep -i bouncy
which bovo && man bovo | cat | head -n 4 | grep -i bovo
which brainparty && man brainparty | cat | head -n 4 | grep -i brainparty
which brainparty-data && man brainparty-data | cat | head -n 4 | grep -i brainparty-data
which briquolo && man briquolo | cat | head -n 4 | grep -i briquolo
which briquolo-data && man briquolo-data | cat | head -n 4 | grep i briquolo-data
which brutalchess && man brutalchess | cat | head -n 4 | grep -i brutalchess
which bsdgames && man bsdgames | cat | head -n 4 | grep -i bsdgames
which bsdgames-nonfree && man bsdgames-nonfree | cat | head -n 4 | grep -i bsdgames-nonfree
which btanks && man btanks | cat | head -n 4 | grep -i btanks
which btanks-data && man btanks-data | cat | head -n 4 | grep -i btanks-data
which bubbros && man bubbros | cat | head -n 4 | grep -i bubbros
which bucklespring && man bucklespring | cat | head -n 4 | grep -i bucklespring
which bucklespring-data && man bucklespring-data | cat | head -n 4 | grep -i bucklespring-data
which bugsquish && man bugsquish | cat | head -n 4 | grep -i bugsquish
which bumprace && man bumprace | cat | head -n 4 | grep -i bumprace
which bumprace-data && man bumprace-data | cat | head -n 4 | grep -i bumprace-data
which burgerspace && man burgerspace | cat | head -n 4 | grep -i burgerspace
which bygfoot && man bygfoot | cat | head -n 4 | grep -i bygfoot
which bygfoot-data && man bygfoot-data | cat | head -n 4 | grep -i bygfoot-data
which bzflag && man bzflag | cat | head -n 4 | grep -i bzflag
which bzflag-client && man bzflag-client | cat | head -n 4 | grep -i bzflag-client
which bzflag-data && man bzflag-data | cat | head -n 4 | grep -i bzflag-data
which bzflag-server && man bzflag-server | cat | head -n 4 | grep -i bzflag-server
which cappuccino && man cappuccino | cat | head -n 4 | grep -i cappuccino
which caveexpress && man caveexpress | cat | head -n 4 | grep -i caveexpress
which caveexpress-data && man caveexpress-data | cat | head -n 4 | grep -i caveexpress-data
which cavepacker && man cavepacker | cat | head -n 4 | grep -i cavepacker
which cavepacker-data && man cavepacker-data | cat | head -n 4 | grep -i cavepacker-data
which cavezofphear && man cavezofphear | cat | head -n 4 | grep -i cavezofphear
which ceferino && man ceferino | cat | head -n 4 | grep -i ceferino
which ceferino-data && man ceferino-data | cat | head -n 4 | grep -i ceferino-data
which cgoban && man cgoban | cat | head -n 4 | grep -i cgoban
which chessx && man chessx | cat | head -n 4 | grep -i chessx
which childsplay && man childsplay | cat | head -n 4 | grep -i childsplay
which childsplay-alphabet-sounds-bg && man childsplay-alphabet-sounds-bg | cat | head -n 4 | grep -i childsplay-alphabet-sounds-bg
which childsplay-alphabet-sounds-el && man childsplay-alphabet-sounds-el | cat | head -n 4 | grep -i childsplay-alphabet-sounds-el
which childsplay-alphabet-sounds-en-gb && man childsplay-alphabet-sounds-en-gb | cat | head -n 4 | grep -i childsplay-alphabet-sounds-en-gb
which childsplay-alphabet-sounds-nb && man childsplay-alphabet-sounds-nb | cat | head -n 4 | grep -i childsplay-alphabet-sounds-nb
which childsplay-alphabet-sounds-ro && man childsplay-alphabet-sounds-ro | cat | head -n 4 | grep -i childsplay-alphabet-sounds-ro
which childsplay-alphabet-sounds-sl && man childsplay-alphabet-sounds-sl | cat | head -n 4 | grep -i childsplay-alphabet-sounds-sl
which chipw && man chipw | cat | head -n 4 | grep -i chipw
which chocolate-common && man chocolate-common | cat | head -n 4 | grep -i chocolate-common
which chocolate-doom && man chocolate-doom | cat | head -n 4 | grep -i chocolate-doom
which chromium-bsu && man chromium-bsu | cat | head -n 4 | grep -i chromium-bsu
which fhromium-bsu-data && man fhromium-bsu-data | cat | head -n 4 | grep -i fhromium-bsu-data
which circuslinux && man circuslinux | cat | head -n 4 | grep -i circuslinux
which circuslinux-data && man circuslinux-data | cat | head -n 4 | grep -i circuslinux-data
which colobot && man colobot | cat | head -n 4 | grep -i colobot
which colobot-common && man colobot-common | cat | head -n 4 | grep -i colobot-common
which colobot-common-sounds && man colobot-common-sounds | cat | head -n 4 | grep -i colobot-common-sounds
which colobot-common-textures && man colobot-common-textures | cat | head -n 4 | grep -i  colobot-common-textures
which colorcode && man colorcode | cat | head -n 4 | grep -i colorcode
which colossal-cave-adventure && man colossal-cave-adventure | cat | head -n 4 | grep -i colossal-cave-adventure
which connectagram && man connectagram | cat | head -n 4 | grep -i connectagram
which connectagram-data && man connectagram-data | cat | head -n 4 | grep -i connectagram-data
which cookietool && man cookietool | cat | head -n 4 | grep -i cookietool
which corsix-th && man corsix-th | cat | head -n 4 | grep -i corsix-th
which corsix-th-data && man corsix-th-data | cat | head -n 4 | grep -i corsix-th-data
which cowsay && man cowsay | cat | head -n 4 | grep -i cowsay
which cowsay-off && man cowsay-off | cat | head -n 4 | grep -i cowsay-off
which crack-attack && man crack-attack | cat | head -n 4 | grep -i crack-attack
which crafty && man crafty | cat | head -n 4 | grep -i crafty
which crafty-bitmaps && man crafty-bitmaps | cat | head -n 4 | grep -i crafty-bitmaps
which crafty-books-medium && man crafty-books-medium | cat | head -n 4 | grep -i crafty-books-medium
which crafty-books-medtosmall && man crafty-books-medtosmall | cat | head -n 4 | grep -i crafty-books-medtosmall
which crafty-books-small && man crafty-books-small | cat | head -n 4 | grep -i crafty-books-small
which crawl && man crawl | cat | head -n 4 | grep -i crawl
which crawl-common && man crawl-common | cat | head -n 4 | grep -i crawl-common
which crawl-tiles && man crawl-tiles | cat | head -n 4 | grep -i crawl-tiles
which crawl-tiles-data && man crawl-tiles-data | cat | head -n 4 | grep -i crawl-tiles-data
which crimson && man crimson | cat | head -n 4 | grep -i crimson
which criticalmass && man criticalmass | cat | head -n 4 | grep -i criticalmass
which criticalmass-data && man criticalmass-data | cat | head -n 4 | grep -i criticalmass-data
which crossfire-client && man crossfire-client | cat | head -n 4 | grep -i crossfire-client
which crossfire-client-images && man crossfire-client-images | cat | head -n 4 | grep -i crossfire-client-images
which crossfire-client-sounds && man crossfire-client-sounds | cat | head -n 4 | grep -i crossfire-client-sounds
which crossfire-common && man crossfire-common | cat | head -n 4 | grep -i crossfire-common
which crossfire-maps && man crossfire-maps | cat | head -n 4 | grep -i crossfire-maps
which crossfire-maps-small && man crossfire-maps-small | cat | head -n 4 | grep -i crossfire-maps-small
which crossfire-server && man crossfire-server | cat | head -n 4 | grep -i crossfire-server
which crrcsim && man crrcsim | cat | head -n 4 | grep -i crrcsim
which crrcsim-data && man crrcsim-data | cat | head -n 4 | grep -i crrcsim-data
which csmash && man csmash | cat | head -n 4 | grep -i csmash
which csmash-data && man csmash-data | cat | head -n 4 | grep -i csmash-data
which csmash-demosong && man csmash-demosong | cat | head -n 4 | grep -i csmash-demosong
which cube2 && man cube2 | cat | head -n 4 | grep -i cube2
which cube2-data && man cube2-data | cat | head -n 4 | grep -i cube2-data
which cube2-server && man cube2-server | cat | head -n 4 | grep -i cube2-server
which cultivation && man cultivation | cat | head -n 4 | grep -i cultivation
which curseofwar && man curseofwar | cat | head -n 4 | grep -i curseofwar
which cutemaze && man cutemaze | cat | head -n 4 | grep -i cutemaze
which cuyo && man cuyo | cat | head -n 4 | grep -i cuyo
which cuyo-data && man cuyo-data | cat | head -n 4 | grep -i cuyo-data
which cytadela && man cytadela | cat | head -n 4 | grep -i cytadela
which cytadela-data && man cytadela-data | cat | head -n 4 | grep -i cytadela-data
which d1x-rebirth && man d1x-rebirth | cat | head -n 4 | grep -i d1x-rebirth
which d2x-rebirth && man d2x-rebirth | cat | head -n 4 | grep -i d2x-rebirth
which dangen && man dangen | cat | head -n 4 | grep -i dangen
which darkplaces && man darkplaces | cat | head -n 4 | grep -i darkplaces
which darkplaces-server && man darkplaces-server | cat | head -n 4 | grep -i darkplaces-server
which dds && man dds | cat | head -n 4 | grep -i dds
which deal && man deal | cat | head -n 4 | grep -i deal
which dealer && man dealer | cat | head -n 4 | grep -i dealer
which defendguin && man defendguin | cat | head -n 4 | grep -i defendguin
which defendguin-data && man defendguin-data | cat | head -n 4 | grep -i defendguin-data
which desmume && man desmume | cat | head -n 4 | grep -i desmume
which deutex && man deutex | cat | head -n 4 | grep -i deutex
which dhewm3 && man dhewm3 | cat | head -n 4 | grep -i dhewm3
which dhewm3-d3xp && man dhewm3-d3xp | cat | head -n 4 | grep -i dhewm3-d3xp
which dhewm3-doom3 && man dhewm3-doom3 | cat | head -n 4 | grep -i dhewm3-doom3
which dizzy && man dizzy | cat | head -n 4 | grep -i dizzy
which dodgindiamond2 && man dodgindiamond2 | cat | head -n 4 | grep -i dodgindiamond2
which dolphin-emu && man dolphin-emu | cat | head -n 4 | grep -i dolphin-emu
which dolphin-emu-data && man dolphin-emu-data | cat | head -n 4 | grep -i dolphin-emu-data
which doom-wad-shareware && man doom-wad-shareware | cat | head -n 4 | grep -i doom-wad-shareware
which dopewars && man dopewars | cat | head -n 4 | grep -i dopewars
which dopewars-data  && man dopewars-data  | cat | head -n 4 | grep -i dopewars-data 
which dossizola && man dossizola | cat | head -n 4 | grep -i dossizola
which dossizola-data && man dossizola-data | cat | head -n 4 | grep -i dossizola-data
which drascula && man drascula | cat | head -n 4 | grep -i drascula
which drascula-french  && man drascula-french  | cat | head -n 4 | grep -i drascula-french 
which drascula-german && man drascula-german | cat | head -n 4 | grep -i drascula-german
which drascula-italian  && man drascula-italian  | cat | head -n 4 | grep -i drascula-italian 
which drascula-music && man drascula-music | cat | head -n 4 | grep -i drascula-music
which drascula-spanish && man drascula-spanish | cat | head -n 4 | grep -i drascula-spanish
which dreamchess && man dreamchess | cat | head -n 4 | grep -i dreamchess
which dreamchess-data && man dreamchess-data | cat | head -n 4 | grep -i dreamchess-data
which dvorak7min && man dvorak7min | cat | head -n 4 | grep -i dvorak7min
which eboard && man eboard | cat | head -n 4 | grep -i eboard
which eboard-extras-pack1 && man eboard-extras-pack1 | cat | head -n 4 | grep -i eboard-extras-pack1
which efp && man efp | cat | head -n 4 | grep -i efp
which einstein && man einstein | cat | head -n 4 | grep -i einstein
which eleeye && man eleeye | cat | head -n 4 | grep -i eleeye
which ember && man ember| cat | head -n 4 | grep -i ember
which ember-media && ember-media | cat | head -n 4 | grep -i ember-media
which empire && man empire | cat | head -n 4 | grep -i empire
which empire-hub && man empire-hub | cat | head -n 4 | grep -i empire-hub
which empire-lafe && man empire-lafe | cat | head -n 4 | grep -i empire-lafe
which endless-sky && man endless-sky | cat | head -n 4 | grep -i endless-sky
which endless-sky-data && man endless-sky-data | cat | head -n 4 | grep -i endless-sky-data
which endless-sky-high-dpi && man endless-sky-high-dpi | cat | head -n 4 | grep -i endless-sky-high-dpi
which enemylines3 && man enemylines3 | cat | head -n 4 | grep -i enemylines3
which enemylines7 && man enemylines7 | cat | head -n 4 | grep -i enemylines7
which enigma && man enigma | cat | head -n 4 | grep -i enigma
which enigma-data && man enigma-data | cat | head -n 4 | grep -i enigma-data
which epiphany && man epiphany | cat | head -n 4 | grep -i epiphany
which epiphany-data && man epiphany-data | cat | head -n 4 | grep -i epiphany-data
which etoys && man etoys | cat | head -n 4 | grep -i etoys
which etqw && man etqw | cat | head -n 4 | grep -i etqw
which etqw-server  && man etqw-server  | cat | head -n 4 | grep -i etqw-server 
which etw && man etw | cat | head -n 4 | grep -i etw
which etw-data && man etw-data | cat | head -n 4 | grep -i etw-data
which excellent-bifurcation && man excellent-bifurcation | cat | head -n 4 | grep -i excellent-bifurcation
which extremetuxracer && man extremetuxracer | cat | head -n 4 | grep -i extremetuxracer
which extremetuxracer-data && man extremetuxracer-data | cat | head -n 4 | grep -i extremetuxracer-data
which exult && man exult | cat | head -n 4 | grep -i exult
which exult-studio && man exult-studio | cat | head -n 4 | grep -i exult-studio
which ezquake && man ezquake | cat | head -n 4 | grep -i ezquake
which fairymax && man fairymax | cat | head -n 4 | grep -i fairymax
which fb-music-high && man fb-music-high | cat | head -n 4 | grep -i fb-music-high
which fceux && man fceux | cat | head -n 4 | grep -i fceux
which ffrenzy && man ffrenzy | cat | head -n 4 | grep -i ffrenzy
which fgo && man fgo | cat | head -n 4 | grep -i fgo
which fheroes2-pkg && man fheroes2-pkg | cat | head -n 4 | grep -i fheroes2-pkg
which filler && man filler | cat | head -n 4 | grep -i filler
which fillets-ng && man fillets-ng | cat | head -n 4 | grep -i fillets-ng
which fillets-ng-data && man fillets-ng-data | cat | head -n 4 | grep -i fillets-ng-data
which fillets-ng-data-cs && man fillets-ng-data-cs | cat | head -n 4 | grep -i fillets-ng-data-cs
which fillets-ng-data-nl && man fillets-ng-data-nl | cat | head -n 4 | grep -i fillets-ng-data-nl
which filters && man filters | cat | head -n 4 | grep -i filters
which five-or-more  && man five-or-more  | cat | head -n 4 | grep -i five-or-more 
which fizmo-common && man fizmo-common | cat | head -n 4 | grep -i fizmo-common
which fizmo-console && man fizmo-console | cat | head -n 4 | grep -i fizmo-console
which fizmo-ncursesw && man fizmo-ncursesw | cat | head-n 4 | grep -i fizmo-ncursesw
which flare && man flare | cat | head -n 4 | grep -i flare
which flare-data && man flare-data | cat | head -n 4 | grep -i flare-data
which flare-engine && man flare-engine | cat | head -n 4 | grep -i flare-engine
which flare-game && man flare-game | cat | head -n 4 | grep -i flare-game
which flight-of-the-amazon-queen && man flight-of-the-amazon-queen | cat | head -n 4 | grep -i flight-of-the-amazon-queen
which flightgear && man flightgear | cat | head -n 4 | grep -i flightgear
which flightgear-data-ai && man flightgear-data-ai | cat | head -n 4 | grep -i flightgear-data-ai
which flightgear-data-all && manflightgear-data-all | cat | head -n 4 | grep -i flightgear-data-all
which flightgear-data-base && man flightgear-data-base | cat | head -n 4 | grep -i flightgear-data-base
which flightgear-data-models && man flightgear-data-models | cat | head -n 4 | grep -i flightgear-data-models
which flightgear-phi  && man flightgear-phi  | cat | head -n 4 | grep -i flightgear-phi 
which flobopuyo &&  man flobopuyo | cat | head -n 4 | grep -i flobopuyo
which fltk1.1-games && man fltk1.1-games | cat | head -n 4 | grep -i fltk1.1-games
which fltk1.3-games && man fltk1.3-games | cat | head -n 4 | grep -i fltk1.3-games
which fofix && man fofix | cat | head -n 4 | grep -i fofix
which foobillardplus && man foobillardplus | cat | head -n 4 | grep -i foobillardplus
which foobillardplus-data && man foobillardplus-data | cat | head -n 4 | grep -i foobillardplus-data
which fortune-mod  && man fortune-mod  | cat | head -n 4 | grep -i fortune-mod 
which fortune-zh && man fortune-zh | cat | head -n 4 | grep -i fortune-zh
which fortunes && man fortunes | cat | head -n 4 | grep -i fortunes
which fortunes-bg && man fortunes-bg | cat | head -n 4 | grep -i fortunes-bg
which fortunes-bofh-excuses && man fortunes-bofh-excuses | cat | head -n 4 | grep -i fortunes-bofh-excuses
which fortunes-br && man fortunes-br | cat | head -n 4 | grep -i fortunes-br
which fortunes-cs && man fortunes-cs | cat | head -n 4 | grep -i fortunes-cs
which fortunes-de&& man fortunes-de | cat | head -n 4 | grep -i fortunes-de
which fortunes-debian-hints && man fortunes-debian-hints | cat | head -n 4 | grep -i fortunes-debian-hints
which fortunes-eo && man fortunes-eo | cat | head -n 4 | grep -i fortunes-eo
which fortunes-eo-ascii && man fortunes-eo-ascii | cat | head -n 4 | grep -i fortunes-eo-ascii
which fortunes-eo-iso3 && man fortunes-eo-iso3 | cat | head -n 4 | grep -i fortunes-eo-iso3
which fortunes-es && man fortunes-es | cat | head -n 4 | grep -i fortunes-es
which fortunes-es-off && man fortunes-es-off | cat | head -n 4 | grep -i fortunes-es-off
which fortunes-fr && man fortunes-fr | cat | head -n 4 | grep -i fortunes-fr
which fortunes-ga && man fortunes-ga | cat | head -n 4 | grep -i fortunes-ga
which fortunes-it && man fortunes-it | cat | head -n 4 | grep -i fortunes-it
which fortunes-it-off && man fortunes-it-off | cat | head -n 4 | grep -i fortunes-it-off
which fortunes-mario && man fortunes-mario | cat | head -n 4 | grep -i fortunes-mario
which fortunes-min && man fortunes-min | head -n 4 | grep -i fortunes-min
which fortunes-off && man fortunes-off | head -n 4 | grep -i fortunes-off
which fortunes-pl && man fortunes-pl | cat | head -n 4 | grep -i fortunes-pl
which fortunes-ru && man fortunes-ru | cat | head -n 4 | grep -i fortunes-ru
which four-in-a-row && man four-in-a-row | cat | head -n 4 | grep -i four-in-a-row
which freealchemist && man freealchemist | cat | head -n 4 | grep -i freealchemist
which freecell-solver-bin && man freecell-solver-bin | cat | head -n 4 | grep -i freecell-solver-bin
which freeciv && man freeciv | cat | head -n 4 | grep -i freeciv
which freeciv-client-extras && man freeciv-client-extras | cat | head -n 4 | grep -i freeciv-client-extras
which freeciv-client-gtk && man freeciv-client-gtk | cat | head -n 4 | grep -i freeciv-client-gtk
which freeciv-client-gtk3 && man freeciv-client-gtk3 | cat | head -n 4 | grep -i freeciv-client-gtk3
which freeciv-client-qt && man freeciv-client-qt | cat | head -n 4 | grep -i freeciv-client-qt
which freeciv-client-sdl && man freeciv-client-sdl | cat | head -n 4 | grep -i freeciv-client-sdl
which freeciv-data && man freeciv-data | cat | head -n 4 | grep -i freeciv-data
which freeciv-server && man freeciv-server | cat | head -n 4 | grep -i freeciv-server
which freeciv-sound-standard && man freeciv-sound-standard | cat | head -n 4 | grep -i freeciv-sound-standard
which freecol && man freecol | cat | head -n 4 | grep -i freecol
which freedink && man freedink | cat | head -n 4 | grep -i freedink
which freedink-data && man freedink-data | cat | head -n 4 | grep -i freedink-data
which freedink-dfarc && man freedink-dfarc | cat | head -n 4 | grep -i freedink-dfarc
which freedink-dfarc && man freedink-dfarc | cat | head -n 4 | grep -i freedink-dfarc
which freedm && man freedm | cat | head -n 4 | grep -i freedm
which freedoom && man freedoom | cat | head -n 4 | gerp -i freedoom
which freedroid && man freedroid | cat | head -n 4 | grep -i freedroid
which freedroid-data && man freedroid-data | cat | head -n 4 | grep -i freedroid-data
which freedroidrpg && man freedroidrpg | cat | head -n 4 | grep -i freedroidrpg
which freedroidrpg-data && man freedroidrpg-data | cat | head -n 4 | grep -i freedroidrpg-data
which freegish && man freegish | cat | head -n 4 | grep -i freegish
which freegish-data  && man freegish-data  | cat | head -n 4 | grep -i freegish-data 
which freeorion && man freeorion | cat | head -n 4 | grep -i freeorion
which freeorion-data && man freeorion-data | cat | head -n 4 | grep -i freeorion-data
which freespace2-launcher-wxlauncher && man freespace2-launcher-wxlauncher | cat | head -n 4 | grep -i freespace2-launcher-wxlauncher
which freesweep && man freesweep | cat | head -n 4 | grep -i freesweep
which freetennis && man freetennis | cat | head -n 4 | grep -i freetennis
which freetennis-common && man freetennis-common | cat | head -n 4 | grep -i freetennis-common
which freevial && man freevial | cat | head -n 4 | grep -i freevial
which fretsonfire && man fretsonfire | cat | head -n 4 | grep -i fretsonfire
which fretsonfire-game && man fretsonfire-game | cat | head -n 4 | grep -i fretsonfire-game
which fretsonfire-songs-muldjord && man fretsonfire-songs-muldjord | cat | head -n 4 | grep -i fretsonfire-songs-muldjord
which fretsonfire-songs-sectoid && man fretsonfire-songs-sectoid | cat | head -n 4 | grep -i fretsonfire-songs-sectoid
which frogatto && man frogatto | cat | head -n 4 | grep -i frogatto
which frogatto-data && man frogatto-data | cat | head -n 4 | grep -i frogatto-data
which frotz && man frotz | cat | head -n 4 | grep -i frotz
which frozen-bubble && man frozen-bubble | cat | head -n 4 | grep -i frozen-bubble
which frozen-bubble-data && man frozen-bubble-data | cat | head -n 4 | grep -i frozen-bubble-data
which fruit && man fruit | cat | head -n 4 | grep -i fruit
which funguloids && man funguloids | cat | head -n 4 | grep -i funguloids
which funguloids-data && man funguloids-data  | cat | head -n 4 | grep -i funguloids-data 
which funnyboat && man funnyboat | cat | head -n 4 | grep -i funnyboat
which gamazons && man gamazons | cat | head -n 4 | grep -i gamazons
which game-data-packager && man game-data-packager | cat | head -n 4 | grep -i game-data-packager
which game-data-packager-runtime && man game-data-packager-runtime | cat | head -n 4 | grep -i game-data-packager-runtime
which gameclock && man gameclock | cat | head -n 4 | grep -i gameclock
which gamine && man gamine | cat | head -n 4 | grep -i gamine
which gamine-data && man gamine-data | cat | head -n 4 | grep -i gamine-data
which garden-of-coloured-lights && man garden-of-coloured-lights | cat | head -n 4 | grep -i garden-of-coloured-lights
which garden-of-coloured-lights-data && man garden-of-coloured-lights-data | cat | head -n 4 | grep -i garden-of-coloured-lights-data
which gargoyle-free && man gargoyle-free | cat | head -n 4 | grep -i gargoyle-free
which gav && man gav | cat | head -n 4 | grep -i gav
which gbatnav && man gbatnav | cat | head -n 4 | grep -i gbatnav
which gbrainy && man gbrainy | cat | head -n 4 | grep -i gbrainy
which gearhead && man gearhead | cat | head -n 4 | grep -i gearhead
which gearhead-data && man gearhead-data | cat | head -n 4 | grep -i gearhead-data
which gearhead-sdl && man gearhead-sdl | cat | head -n 4 | grep -i gearhead-sdl
which gearhead2 && man gearhead2 | cat | head -n 4 | grep -i gearhead2
which gearhead2-data && man gearhead2-data | cat | head -n 4 | grep -i gearhead2-data
which gearhead2-sdl && man gearhead2-sdl | cat | head -n 4 | grep -i gearhead2-sdl
which geekcode && man geekcode | cat | head -n 4 | grep -i geekcode
which geki2 && man geki2 | cat | head -n 4 | grep -i geki2
which geki3 && man geki3 | cat | head -n 4 | grep -i geki3
which gemdropx && man gemdropx | cat | head -n 4 | grep -i gemdropx
which gemrb && man gemrb | cat | head -n 4 | grep -i gemrb
which gemrb-baldurs-gate && man gemrb-baldurs-gate | cat | head -n 4 | grep -i gemrb-baldurs-gate
which gemrb-baldurs-gate-2 && man gemrb-baldurs-gate-2 | cat | head -n 4 | grep -i gemrb-baldurs-gate-2
which gemrb-baldurs-gate-2-data && man gemrb-baldurs-gate-2-data | cat | head -n 4 | grep -i gemrb-baldurs-gate-2-data
which gemrb-baldurs-gate-data && man gemrb-baldurs-gate-data | cat | head -n 4 | grep -i gemrb-baldurs-gate-data
which gemrb-data && man gemrb-data  | cat | head -n 4 | grep -i gemrb-data 
which gemrb-icewind-dale && man gemrb-icewind-dale | cat | head -n 4 | grep -i gemrb-icewind-dale
which gemrb-icewind-dale-2 && man gemrb-icewind-dale-2 | cat | head -n 4 | grep -i gemrb-icewind-dale-2
which gemrb-icewind-dale-2-data && man gemrb-icewind-dale-2-data | cat | head -n 4 | grep -i gemrb-icewind-dale-2-data
which gemrb-icewind-dale-data && man gemrb-icewind-dale-data | cat | head -n 4 | grep -i gemrb-icewind-dale-data
which gemrb-planescape-torment && man gemrb-planescape-torment | cat | head -n 4 | grep -i gemrb-planescape-torment
which gemrb-planescape-torment-data && man gemrb-planescape-torment-data | cat | head -n 4 | grep -i gemrb-planescape-torment-data
which gfpoken && man gfpoken | cat | head -n 4 | grep -i gfpoken
which ghextris && man ghextris | cat | head -n 4 | grep -i ghextris
which gl-117 && man gl-117 | cat | head -n 4 | grep -i gl-117
which gl-117-data && man gl-117-data | cat | head -n 4 | grep -i gl-117-data
which glaurung && man glaurung | cat | head -n 4 | grep -i glaurung
which glhack && man glhack | cat | head -n 4 | grep -i glhack
which glob2 && man glob2 | cat | head -n 4 | grep -i glob2
which glob2-data && man glob2-data | cat | head -n 4 | grep -i glob2-data
which glpeces && man glpeces | cat | head -n 4 | grep -i glpeces
which glpeces-data && man glpeces-data | cat | head -n 4 | grep -i glpeces-data
which gltron && man gltron | cat | head -n 4 | grep -i gltron
which gmchess && man gmchess | cat | head -n 4 | grep -i gmchess
which gmult && man gmult | cat | head -n 4 | grep -i gmult
which gnome-2048 && man gnome-2048 | cat | head -n 4 | grep -i gnome-2048
which gnome-breakout && man gnome-breakout | cat | head -n 4 | grep -i gnome-breakout
which gnome-cards-data && man gnome-cards-data | cat | head -n 4 | grep -i gnome-cards-data
which gnome-chess && man gnome-chess | cat | head -n 4 | grep -i gnome-chess
which gnome-hearts && man gnome-hearts | cat | head -n 4 | grep -i gnome-hearts
which gnome-klotski && man gnome-klotski | cat | head -n 4 | grep -i gnome-klotski
which gnome-mahjongg && man gnome-mahjongg | cat | head -n 4 | grep -i gnome-mahjongg
which gnome-mastermind && man gnome-mastermind | cat | head -n 4 | grep -i gnome-mastermind
which gnome-mines && man gnome-mines | cat | head -n 4 | grep -i gnome-mines
which gnome-nibbles && man gnome-nibbles | cat | head -n 4 | grep -i gnome-nibbles
which gnome-robots && man gnome-robots | cat | head -n 4 | grep -i gnome-robots
which gnome-sudoku && man gnome-sudoku | cat | head -n 4 | grep -i gnome-sudoku
which gnome-taquin && man gnome-taquin | cat | head -n 4 | grep -i gnome-taquin
which gnome-tetravex && man gnome-tetravex | cat | head -n 4 | grep -i gnome-tetravex
which gnubg && man gnubg | cat | head -n 4 | grep -i gnubg
which gnubg-data && man gnubg-data | cat | head -n 4 | grep -i gnubg-data
which gnubik && man gnubik | cat | head -n 4 | grep -i gnubik
which gnuboy-sdl && man gnuboy-sdl | cat | head -n 4 | grep -i gnuboy-sdl
which gnuboy-x && man gnuboy-x | cat | head -n 4 | grep -i gnuboy-x
which gnuchess && man gnuchess | cat | head -n 4 | grep -i gnuchess
which gnuchess-book && man gnuchess-book | cat | head -n 4 | grep -i gnuchess-book
which gnudoq && man gnudoq | cat | head -n 4 | grep -i gnudoq
which gnugo && man gnugo | cat | head -n 4 | grep -i gnugo
which gnujump && man gnujump | cat | head -n 4 | grep -i gnujump
which gnujump-data && man gnujump-data | cat | head -n 4 | grep -i gnujump-data
which gnuminishogi && man gnuminishogi | cat | head -n 4 | grep -i gnuminishogi
which gnurobbo && man gnurobbo | cat | head -n 4 | grep -i gnurobbo
which gnurobbo-data && man gnurobbo-data | cat | head -n 4 | grep -i gnurobbo-data
which gnushogi && man gnushogi | cat | head -n 4 | grep -i gnushogi
which golly && man golly | cat | head -n 4 | grep -i golly
which gplanarity && man gplanarity | cat | head -n 4 | grep -i gplanarity
which granatier && man granatier | cat | head -n 4 | grep -i granatier
which gravitation && man gravitation | cat | head -n 4 | grep -i gravitation
which gravitywars && man gravitywars | cat | head -n 4 | grep -i gravitywars
which greed && man greed | cat | head -n 4 | grep -i greed
which grhino && man grhino | cat | head -n 4 | grep -i grhino
which grhino-data && man grhino-data | cat | head -n 4 | grep -i grhino-data
which groundhog && man groundhog | cat | head -n 4 | grep -i groundhog
which gsalliere && man gsalliere | cat | head -n 4 | grep -i gsalliere
which gtans && man gtans | cat | head -n 4 | grep -i gtans
which gtkatlantic && man gtkatlantic | cat | head -n 4 | grep -i gtkatlantic
which gtkballs && man gtkballs | cat | head -n 4 | grep -i gtkballs
which gtkboard && man gtkboard | cat | head -n 4 | grep -i gtkboard
which gtkpool && man gtkpool | cat | head -n 4 | grep -i gtkpool
which gunroar && man gunroar | cat | head -n 4 | grep -i gunroar
which gunroar-data && man gunroar-data | cat | head -n 4 | grep -i gunroar-data
which gvrng && man gvrng | cat | head -n 4 | grep -i gvrng
which gweled && man gweled | cat | head -n 4 | grep -i gweled
which hachu && man hachu | cat | head -n 4 | grep -i hachu
which hannah && man hannah | cat | head -n 4 | grep -i hannah
which hannah-data && man hannah-data | cat | head -n 4 | grep -i hannah-data
which hearse && man hearse | cat | head -n 4 | grep -i hearse
which hedgewars && man hedgewars | cat | head -n 4 | grep -i hedgewars
which hedgewars-data && man hedgewars-data | cat | head -n 4 | grep -i hedgewars-data
which heroes && man heroes | cat | head -n 4 | grep -i heroes
which heroes-common && man heroes-common | cat | head -n 4 | grep -i heroes-common
which heroes-data && man heroes-data | cat | head -n 4 | grep -i heroes-data
which heroes-sdl && man heroes-sdl | cat | head -n 4 | grep -i heroes-sdl
which heroes-sound-effects && man heroes-sound-effects | cat | head -n 4 | grep -i heroes-sound-effects
which heroes-sound-tracks && man heroes-sound-tracks | cat | head -n 4 | grep -i heroes-sound-tracks
which hex-a-hop && man hex-a-hop | cat | head -n 4 | grep -i hex-a-hop
which hexalate && man hexalate | cat | head -n 4 | grep -i hexalate
which hexxagon && man hexxagon | cat | head -n 4 | grep -i hexxagon
which hitori && man hitori | cat | head -n 4 | grep -i hitori
which hoichess && man hoichess | cat | head -n 4 | grep -i hoichess
which holdingnuts && man holdingnuts | cat | head -n 4 | grep -i holdingnuts
which holdingnuts-server && man holdingnuts-server | cat | head -n 4 | grep -i holdingnuts-server
which holotz-castle && man holotz-castle | cat | head -n 4 | grep -i holotz-castle
which holotz-castle-data && man holotz-castle-data | cat | head -n 4 | grep -i holotz-castle-data
which holotz-castle-editor && man holotz-castle-editor | cat | head -n 4 | grep -i holotz-castle-editor
which hyperrogue && man hyperrogue | cat | head -n 4 | grep -i hyperrogue
which hyperrogue-music && man hyperrogue-music | cat | head -n 4 | grep -i hyperrogue-music
which iagno && man iagno | cat | head -n 4 | grep -i iagno
which ii-esu && man ii-esu | cat | head -n 4 | grep -i ii-esu
which infon-server && man infon-server | cat | head -n 4 | grep -i infon-server
which infon-viewer && man infon-viewer | cat | head -n 4 | grep -i infon-viewer
which instead && man instead | cat | head -n 4 | grep -i instead
which instead-data && man instead-data | cat | head -n 4 | grep -i instead-data
which ioquake3 && man ioquake3 | cat | head -n 4 | grep -i ioquake3
which ioquake3-server && man ioquake3-server | cat | head -n 4 | grep -i ioquake3-server
which jester && man jester | cat | head -n 4 | grep -i jester
which jigzo && man jigzo | cat | head -n 4 | grep -i jigzo
which jigzo-data && man jigzo-data | cat | head -n 4 | grep -i jigzo-data
which jmdlx && man jmdlx | cat | head -n 4 | grep -i jmdlx
which jmdlx && man jmdlx | cat | head -n 4 | grep -i jmdlx
which jumpnbump-levels && man jumpnbump-levels | cat | head -n 4 | grep -i jumpnbump-levels
which junior-toys && man junior-toys | cat | head -n 4 | grep -i junior-toys
which jzip && man jzip | cat | head -n 4 | grep -i jzip
which kajongg && man kajongg | cat | head -n 4 | grep -i kajongg
which kanagram && man kanagram | cat | head -n 4 | grep -i kanagram
which kapman && man kapman | cat | head -n 4 | grep -i kapman
which katomic && man katomic | cat | head -n 4 | grep -i katomic
which kawari8 && man kawari8 | cat | head -n 4 | grep -i kawari8
which kball && man kball | cat | head -n 4 | grep -i kball
which kball-data && man kball-data | cat | head -n 4 | grep -i kball-data
which kbattleship && man kbattleship | cat | head -n 4 | grep -i kbattleship
which kblackbox && man kblackbox | cat | head -n 4 | grep -i kblackbox
which kblocks && man kblocks | cat | head -n 4 | grep -i kblocks
which kbounce && man kbounce | cat | head -n 4 | grep -i kbounce
which kbreakout && man kbreakout | cat | head -n 4 | grep -i kbreakout
which kcheckers && man kcheckers | cat | head -n 4 | grep -i kcheckers
which kdegames-card-data && man kdegames-card-data | cat | head -n 4 | grep -i kdegames-card-data
which kdegames-card-data-kf5 && man kdegames-card-data-kf5 | cat | head -n 4 | grep -i kdegames-card-data-kf5
which kdegames-mahjongg-data && man kdegames-mahjongg-data | cat | head -n 4 | grep -i kdegames-mahjongg-data
which kdegames-mahjongg-data-kf5 && man kdegames-mahjongg-data-kf5 | cat | head -n 4 | grep -i kdegames-mahjongg-data-kf5
which kdiamond && man kdiamond | cat | head -n 4 | grep -i kdiamond
which ketm && man ketm | cat | head -n 4 | grep -i ketm
which ketm-data && man ketm-data | cat | head -n 4 | grep -i ketm-data
which kfourinline && man kfourinline | cat | head -n 4 | grep -i kfourinline
which kgoldrunner && man kgoldrunner | cat | head -n 4 | grep -i kgoldrunner
which khangman && man khangman | cat | head -n 4 | grep -i khangman
which kigo && man kigo | cat | head -n 4 | grep -i kigo
which kiki-the-nano-bot && man kiki-the-nano-bot | cat | head -n 4 | grep -i kiki-the-nano-bot
which kiki-the-nano-bot-data && man kiki-the-nano-bot-data  | cat | head -n 4 | grep -i kiki-the-nano-bot-data 
which kildclient && man kildclient | cat | head -n 4 | grep -i kildclient
which killbots && man killbots | cat | head -n 4 | grep -i killbots
which kiriki && man kiriki | cat | head -n 4 | grep -i kiriki
which kjumpingcube && man kjumpingcube | cat | head -n 4 | grep -i kjumpingcube
which klickety && man klickety | cat | head -n 4 | grep -i klickety
which klines && man klines | cat | head -n 4 | grep -i klines
which kmahjongg && man kmahjongg | cat | head -n 4 | grep -i kmahjongg
which kmines && man kmines | cat | head -n 4 | grep -i kmines
which knavalbattle && man knavalbattle | cat | head -n 4 | grep -i knavalbattle
which knetwalk && man knetwalk | cat | head -n 4 | grep -i knetwalk
which knights && man knights | cat | head -n 4 | grep -i knights
which kobodeluxe && man kobodeluxe | cat | head -n 4 | grep -i kobodeluxe
which kobodeluxe-data && man kobodeluxe-data | cat | head -n 4 | grep -i kobodeluxe-data
which kolf && man kolf | cat | head -n 4 | grep -i kolf
which kollision && man kollision | cat | head -n 4 | grep -i kollision
which komi && man komi | cat | head -n 4 | grep -i komi
which konquest && man konquest | cat | head -n 4 | grep -i konquest
which koules && man koules | cat | head -n 4 | grep -i koules
which kpat && man kpat | cat | head -n 4 | grep -i kpat
which krank && man krank | cat | head -n 4 | grep -i krank
which kraptor && man kraptor | cat | head -n 4 | grep -i kraptor
which kraptor-data && man kraptor-data | cat | head -n 4 | grep -i kraptor-data
which kreversi && man kreversi | cat | head -n 4 | grep -i kreversi
which kshisen && man kshisen | cat | head -n 4 | grep -i kshisen
which ksirk && man ksirk | cat | head -n 4 | grep -i ksirk
which ksnakeduel && man ksnakeduel | cat | head -n 4 | grep -i ksnakeduel
which kspaceduel && man kspaceduel | cat | head -n 4 | grep -i kspaceduel
which ksquares && man ksquares | cat | head -n 4 | grep -i ksquares
which ksudoku && man ksudoku | cat | head -n 4 | grep -i ksudoku
which ktuberling && man ktuberling | cat | head -n 4 | grep -i ktuberling
which kubrick && man kubrick | cat | head -n 4 | grep -i kubrick
which laby && man laby | cat | head -n 4 | grep -i laby
which late && man late | cat | head -n 4 | grep -i late
which late-data && man late-data | cat | head -n 4 | grep -i late-data
which lbreakout2 && man lbreakout2 | cat | head -n 4 | grep -i lbreakout2
which lbreakout2-data && man lbreakout2-data | cat | head -n 4 | grep -i lbreakout2-data
which lgc-pg && man lgc-pg | cat | head -n 4 | grep -i lgc-pg
which lgeneral && man lgeneral | cat | head -n 4 | grep -i lgeneral
which lgeneral-data && man lgeneral-data | cat | head -n 4 | grep -i lgeneral-data
which libatlas-cpp-0.6-tools && man libatlas-cpp-0.6-tools | cat | head -n 4 | grep -i libatlas-cpp-0.6-tools
which libgemrb && man libgemrb | cat | head -n 4 | grep -i libgemrb
which libmgba && man libmgba | cat | head -n 4 | grep -i libmgba
which libretro-beetle-pce-fast && man libretro-beetle-pce-fast | cat | head -n 4 | grep -i libretro-beetle-pce-fast
which libretro-beetle-psx && man libretro-beetle-psx | cat | head -n 4 | grep -i libretro-beetle-psx
which libretro-beetle-vb && man libretro-beetle-vb | cat | head -n 4 | grep -i libretro-beetle-vb
which libretro-beetle-wswan && man libretro-beetle-wswan | cat | head -n 4 | grep -i libretro-beetle-wswan
which libretro-bsnes-mercury-accuracy && man libretro-bsnes-mercury-accuracy | cat | head -n 4 | grep -i libretro-bsnes-mercury-accuracy
which libretro-bsnes-mercury-balanced && man libretro-bsnes-mercury-balanced | cat | head -n 4 | grep -i libretro-bsnes-mercury-balanced
which libretro-bsnes-mercury-performance && man libretro-bsnes-mercury-performance | cat | head -n 4 | grep -i libretro-bsnes-mercury-performance
which libretro-desmume && man libretro-desmume | cat | head -n 4 | grep -i libretro-desmume
which libretro-gambatte && man libretro-gambatte | cat | head -n 4 | grep -i libretro-gambatte
which libretro-genesisplusgx && man libretro-genesisplusgx | cat | head -n 4 | grep -i libretro-genesisplusgx
which libretro-mgba && man libretro-mgba | cat | head -n 4 | grep -i libretro-mgba
which libretro-mupen64plus && man libretro-mupen64plus | cat | head -n 4 | grep -i libretro-mupen64plus
which libretro-nestopia && man libretro-nestopia | cat | head -n 4 | grep -i libretro-nestopia
which libretro-snes9x && man libretro-snes9x | cat | head -n 4 | grep -i libretro-snes9x
which lightsoff && man lightsoff | cat | head -n 4 | grep -i lightsoff
which lightyears && man lightyears | cat | head -n 4 | grep -i lightyears
which lincity && man lincity | cat | head -n 4 | grep -i lincity
which lincity-ng && man lincity-ng | cat | head -n 4 | grep -i lincity-ng
which lincity-ng-data && man lincity-ng-data | cat | head -n 4 | grep -i lincity-ng-data
which liquidwar && man liquidwar | cat | head -n 4 | grep -i liquidwar
which liquidwar-data && man liquidwar-data | cat | head -n 4 | grep -i liquidwar-data
which liquidwar-server && man liquidwar-server | cat | head -n 4 | grep -i liquidwar-server
which littlewizard && man littlewizard | cat | head -n 4 | grep -i littlewizard
which littlewizard-data  && man littlewizard-data  | cat | head -n 4 | grep -i littlewizard-data 
which lmarbles && man lmarbles | cat | head -n 4 | grep -i lmarbles
which lmemory && man lmemory | cat | head -n 4 | grep -i lmemory
which lolcat && man lolcat | cat | head -n 4 | grep -i lolcat
which londonlaw && man londonlaw | cat | head -n 4 | grep -i londonlaw
which lordsawar && man lordsawar | cat | head -n 4 | grep -i lordsawar
which lordsawar-data && man lordsawar-data | cat | head -n 4 | grep -i lordsawar-data
which love && man love | cat | head -n 4 | grep -i love
which lskat && man lskat | cat | head -n 4 | grep -i lskat
which ltris && man ltris | cat | head -n 4 | grep -i ltris
which luola && man luola | cat | head -n 4 | grep -i luola
which luola-data && man luola-data | cat | head -n 4 | grep -i luola-data
which luola-levels && man luola-levels | cat | head -n 4 | grep -i luola-levels
which luola-nostalgy && man luola-nostalgy | cat | head -n 4 | grep -i luola-nostalgy
which lure-of-the-temptress && man lure-of-the-temptress | cat | head -n 4 | grep -i lure-of-the-temptress
which macopix-gtk2 && man macopix-gtk2 | cat | head -n 4 | grep -i macopix-gtk2
which madbomber && man madbomber | cat | head -n 4 | grep -i madbomber
which madbomber-data && man madbomber-data | cat | head -n 4 | grep -i madbomber-data
which maelstrom && man maelstrom | cat | head -n 4 | grep -i maelstrom
which magicmaze && man magicmaze | cat | head -n 4 | grep -i magicmaze
which magicor && man magicor | cat | head -n 4 | grep -i magicor
which magicor-data && man magicor-data | cat | head -n 4 | grep -i magicor-data
which mah-jong && man mah-jong | cat | head -n 4 | grep -i mah-jong
which mame && man mame | cat | head -n 4 | grep -i mame
which mame-data && man mame-data | cat | head -n 4 | grep -i mame-data
which mame-extra && man mame-extra | cat | head -n 4 | grep -i mame-extra
which manaplus && man manaplus | cat | head -n 4 | grep -i manaplus
which manaplus-data && man manaplus-data | cat | head -n 4 | grep -i manaplus-data
which mancala && man mancala | cat | head -n 4 | grep -i mancala
which marsshooter && man marsshooter | cat | head -n 4 | grep -i marsshooter
which marsshooter-data && man marsshooter-data | cat | head -n 4 | grep -i marsshooter-data
which matanza && man matanza | cat | head -n 4 | grep -i matanza
which mazeofgalious && man mazeofgalious | cat | head -n 4 | grep -i mazeofgalious
which mazeofgalious-data && man mazeofgalious-data | cat | head -n 4 | grep -i mazeofgalious-data
which mednafen && man mednafen | cat | head -n 4 | grep -i mednafen
which mednaffe && man mednaffe | cat | head -n 4 | grep -i mednaffe
which megaglest && man megaglest | cat | head -n 4 | grep -i megaglest
which megaglest-data && man megaglest-data | cat | head -n 4 | grep -i megaglest-data
which meritous && man meritous | cat | head -n 4 | grep -i meritous
which meritous-data && man meritous-data | cat | head -n 4 | grep -i meritous-data
which mgba-common && man mgba-common | cat | head -n 4 | grep -i mgba-common
which mgba-qt && man mgba-qt | cat | head -n 4 | grep -i mgba-qt
which mgba-sdl && man mgba-sdl | cat | head -n 4 | grep -i mgba-sdl
which mgt && man mgt | cat | head -n 4 | grep -i mgt
which miceamaze && man miceamaze | cat | head -n 4 | grep -i miceamaze
which micropolis && man micropolis | cat | head -n 4 | grep -i micropolis
which micropolis-data && man micropolis-data | cat | head -n 4 | grep -i micropolis-data
which minetest && man minetest | cat | head -n 4 | grep -i minetest
which minetest-data && man minetest-data | cat | head -n 4 | grep -i minetest-data
which minetest-mod-advspawning && man minetest-mod-advspawning | cat | head -n 4 | grep -i minetest-mod-advspawning
which minetest-mod-animalmaterials && man minetest-mod-animalmaterials | cat | head -n 4 | grep -i minetest-mod-animalmaterials
which minetest-mod-animals && man minetest-mod-animals | cat | head -n 4 | grep -i minetest-mod-animals
which minetest-mod-maidroid && man minetest-mod-maidroid | cat | head -n 4 | grep -i minetest-mod-maidroid
which minetest-mod-mesecons && man minetest-mod-mesecons | cat | head -n 4 | grep -i minetest-mod-mesecons
which minetest-mod-mobf-core && man minetest-mod-mobf-core | cat | head -n 4 | grep -i minetest-mod-mobf-core
which minetest-mod-mobf-trap && man minetest-mod-mobf-trap | cat | head -n 4 | grep -i minetest-mod-mobf-trap
which minetest-mod-moreblocks && man minetest-mod-moreblocks | cat | head -n 4 | grep -i minetest-mod-moreblocks
which minetest-mod-moreores && man minetest-mod-moreores | cat | head -n 4 | grep -i minetest-mod-moreores
which minetest-mod-nether && man minetest-mod-nether | cat | head -n 4 | grep -i minetest-mod-nether
which minetest-mod-pipeworks && man minetest-mod-pipeworks | cat | head -n 4 | grep -i minetest-mod-pipeworks
which minetest-mod-torches && man minetest-mod-torches | cat | head -n 4 | grep -i minetest-mod-torches
which minetest-mod-worldedit  && man minetest-mod-worldedit  | cat | head -n 4 | grep -i minetest-mod-worldedit 
which minetest-server && man minetest-server | cat | head -n 4 | grep -i minetest-server
which mirrormagic && man mirrormagic | cat | head -n 4 | grep -i mirrormagic
which mirrormagic-data && man mirrormagic-data | cat | head -n 4 | grep -i mirrormagic-data
which mokomaze && man mokomaze | cat | head -n 4 | grep -i mokomaze
which monopd && man monopd | cat | head -n 4 | grep -i monopd
which monster-masher && man monster-masher | cat | head -n 4 | grep -i monster-masher
which monsterz && man monsterz | cat | head -n 4 | grep -i monsterz 
which monsterz-data && man monsterz-data | cat | head -n 4 | grep -i monsterz-data
which moon-buggy && man moon-buggy | cat | head -n 4 | grep -i moon-buggy
which moon-buggy-esd && man moon-buggy-esd | cat | head -n 4 | grep -i moon-buggy-esd
which moon-lander && man moon-lander | cat | head -n 4 | grep -i moon-lander
which moon-lander-data && man moon-lander-data | cat | head -n 4 | grep -i moon-lander-data
which moria && man moria | cat | head -n 4 | grep -i moria
which morris && man morris | cat | head -n 4 | grep -i morris
which mousetrap && man mousetrap | cat | head -n 4 | grep -i mousetrap
which mrrescue && man mrrescue | cat | head -n 4 | grep -i mrrescue
which mu-cade  && man mu-cade  | cat | head -n 4 | grep -i mu-cade 
which mu-cade-data && man mu-cade-data | cat | head -n 4 | grep -i mu-cade-data
which mudlet && man mudlet | cat | head -n 4 | grep -i mudlet
which mupen64plus-audio-sdl && man mupen64plus-audio-sdl | cat | head -n 4 | grep -i mupen64plus-audio-sdl
which mupen64plus-data && man mupen64plus-data | cat | head -n 4 | grep -i mupen64plus-data
which mupen64plus-input-sdl && man mupen64plus-input-sdl | cat | head -n 4 | grep -i mupen64plus-input-sdl
which mupen64plus-qt && man mupen64plus-qt | cat | head -n 4 | grep -i mupen64plus-qt
which mupen64plus-rsp-hle && man mupen64plus-rsp-hle | cat | head -n 4 | grep -i mupen64plus-rsp-hle
which mupen64plus-rsp-z64 && man mupen64plus-rsp-z64 | cat | head -n 4 | grep -imupen64plus-rsp-z64
which mupen64plus-ui-console && man mupen64plus-ui-console | cat | head -n 4 | grep -i mupen64plus-ui-console
which mupen64plus-video-arachnoid && man mupen64plus-video-arachnoid | cat | head -n 4 | grep -i mupen64plus-video-arachnoid
which mupen64plus-video-glide64 && man mupen64plus-video-glide64 | cat | head -n 4 | grep -i mupen64plus-video-glide64
which mupen64plus-video-glide64mk2 && man mupen64plus-video-glide64mk2 | cat | head -n 4 | grep -i mupen64plus-video-glide64mk2
which mupen64plus-video-rice && man mupen64plus-video-rice | cat | head -n 4 | grep -i mupen64plus-video-rice
which mupen64plus-video-z64 && man mupen64plus-video-z64 | cat | head -n 4 | grep -i mupen64plus-video-z64
which nestopia && man nestopia | cat | head -n 4 | grep -i nestopia
which nethack-common && man nethack-common | cat | head -n 4 | grep -i nethack-common
which nethack-console && man nethack-console | cat | head -n 4 | grep -i nethack-console
which nethack-lisp && man nethack-lisp | cat | head -n 4 | grep -i nethack-lisp
which nethack-x11 && man nethack-x11 | cat | head -n 4 | grep -i nethack-x11
which netmaze && man netmaze | cat | head -n 4 | grep -i netmaze
which netpanzer && man netpanzer | cat | head -n 4 | grep -i netpanzer
which netpanzer-data && man netpanzer-data | cat | head -n 4 | grep -i netpanzer-data
which netrek-client-cow && man netrek-client-cow | cat | head -n 4 | grep -i netrek-client-cow
which netris && man netris | cat | head -n 4 | grep -i netris
which nettoe && man nettoe | cat | head -n 4 | grep -i nettoe
which neverball && man neverball | cat | head -n 4 | grep -i neverball
which neverball-common && man neverball-common | cat | head -n 4 | grep -i neverball-common
which neverball-data && man neverball-data | cat | head -n 4 | grep -i neverball-data
which neverputt && man neverputt | cat | head -n 4 | grep -i neverputt
which neverputt-data && man neverputt-data | cat | head -n 4 | grep -i neverputt-data
which nexuiz && man nexuiz | cat | head -n 4 | grep -i nexuiz
which nexuiz-data && man nexuiz-data | cat | head -n 4 | grep -i nexuiz-data
which nexuiz-music && man nexuiz-music | cat | head -n 4 | grep -i nexuiz-music
which nexuiz-server && man nexuiz-server | cat | head -n 4 | grep -i nexuiz-server
which nexuiz-textures && man nexuiz-textures | cat | head -n 4 | grep -i nexuiz-textures
which nikwi && man nikwi | cat | head -n 4 | grep -i nikwi
which nikwi-data && man nikwi-data | cat | head -n 4 | grep -i nikwi-data
which ninix-aya && man ninix-aya | cat | head -n 4 | grep -i ninix-aya
which ninvaders && man ninvaders | cat | head -n 4 | grep -i ninvaders
which njam && man njam | cat | head -n 4 | grep -i njam
which njam-data && man njam-data | cat | head -n 4 | grep -i njam-data
which noiz2sa && man noiz2sa | cat | head -n 4 | grep -i noiz2sa
which noiz2sa-data && man noiz2sa-data | cat | head -n 4 | grep -i noiz2sa-data
which nsnake && man nsnake | cat | head -n 4 | grep -i nsnake
which nudoku && man nudoku | cat | head -n 4 | grep -i nudoku
which numptyphysics && man numptyphysics | cat | head -n 4 | grep -i numptyphysics
which omega-rpg && man omega-rpg | cat | head -n 4 | grep -i omega-rpg
which oneisenough && man oneisenough | cat | head -n 4 | grep -i oneisenough
which oneko && man oneko | cat | head -n 4 | grep -i oneko
which onscripter && man onscripter | cat | head -n 4 | grep -i onscripter
which oolite && man oolite | cat | head -n 4 | grep -i oolite
which oolite-data && man oolite-data | cat | head -n 4 | grep -i oolite-data
which oolite-data-sounds && man oolite-data-sounds | cat | head -n 4 | grep -i oolite-data-sounds
which open-invaders && man open-invaders | cat | head -n 4 | grep -i open-invaders
which open-invaders-data && man open-invaders-data | cat | head -n 4 | grep -i open-invaders-data
which openarena && man openarena | cat | head -n 4 | grep -i openarena
which openarena-081-maps && man openarena-081-maps | cat | head -n 4 | grep -i openarena-081-maps
which openarena-081-misc && man openarena-081-misc | cat | head -n 4 | grep -i openarena-081-misc
which openarena-081-players && man openarena-081-players | cat | head -n 4 | grep -i openarena-081-players
which openarena-081-players-mature && man openarena-081-players-mature | cat | head -n 4 | grep -i openarena-081-players-mature
which openarena-081-textures && man openarena-081-textures | cat | head -n 4 | grep -i openarena-081-textures
which openarena-085-data && man openarena-085-data | cat | head -n 4 | grep -i openarena-085-data
which openarena-088-data && man openarena-088-data | cat | head -n 4 | grep -i openarena-088-data
which openarena-data && man openarena-data | cat | head -n 4 | grep -i openarena-data
which openarena-oacmp1 && man openarena-oacmp1 | cat | head -n 4 | grep -i openarena-oacmp1
which openarena-server && man openarena-server | cat | head -n 4 | grep -i openarena-server
which openbve-data && man openbve-data | cat | head -n 4 | grep -i openbve-data
which opencity && man opencity | cat | head -n 4 | grep -i opencity
which opencity-data && man opencity-data | cat | head -n 4 | grep -i opencity-data
which openclonk && man openclonk | cat | head -n 4 | grep -i openclonk
which openclonk-data && man openclonk-data | cat | head -n 4 | grep -i openclonk-data
which openlugaru && man openlugaru | cat | head -n 4 | grep -i openlugaru
which openlugaru-data && man openlugaru-data | cat | head -n 4 | grep -i openlugaru-data
which openpref && man openpref | cat | head -n 4 | grep -i openpref 
which openssn && man openssn | cat | head -n 4 | grep -i openssn
which openssn-data && man openssn-data | cat | head -n 4 | grep -i openssn-data
which openttd && man openttd | cat | head -n 4 | grep -i openttd
which openttd-data && man openttd-data | cat | head -n 4 | grep -i openttd-data
which openttd-opengfx && man openttd-opengfx | cat | head -n 4 | grep -i openttd-opengfx
which openttd-openmsx && man openttd-openmsx | cat | head -n 4 | grep -i openttd-openmsx
which openttd-opensfx && man openttd-opensfx | cat | head -n 4 | grep -i openttd-opensfx
which opentyrian && man opentyrian | cat | head -n 4 | grep -i opentyrian
which openyahtzee && man openyahtzee | cat | head -n 4 | grep -i openyahtzee
which orbital-eunuchs-sniper && man orbital-eunuchs-sniper | cat | head -n 4 | grep -i orbital-eunuchs-sniper
which orbital-eunuchs-sniper-data && man orbital-eunuchs-sniper-data | cat | head -n 4 | grep -i orbital-eunuchs-sniper-data
which osmose-emulator && man osmose-emulator | cat | head -n 4 | grep -i osmose-emulator
which out-of-order && man out-of-order | cat | head -n 4 | grep -i out-of-order
which overgod && man overgod | cat | head -n 4 | grep -i overgod
which overgod-data && man overgod-data | cat | head -n 4 | grep -i overgod-data
which pachi && man pachi | cat | head -n 4 | grep -i pachi
which pachi-data && man pachi-data | cat | head -n 4 | grep -i pachi-data 
which pacman && man pacman | cat | head -n  4 | grep -i pacman
which pacman4console && man pacman4console | cat | head -n 4 | grep -i pacman4console
which pairs && man pairs | cat | head -n 4 | grep -i pairs
which palapeli && man palapeli | cat | head -n 4 | grep -i palapeli
which palapeli-data && man palapeli-data | cat | head -n 4 | grep -i palapeli-data
which pangzero && man pangzero | cat | head -n 4 | grep -i pangzero
which parsec47 && man parsec47 | cat | head -n 4 | grep -i parsec47
which parsec47-data && man parsec47-data | cat | head -n 4 | grep -i parsec47-data
which passage && man passage | cat | head -n 4 | grep -i passage
which pathogen && man pathogen | cat | head -n 4 | grep -i pathogen
which pathological && man pathological | cat | head -n 4 | grep -i pathological
which pax-britannica && man pax-britannica | cat | head -n 4 | grep -i pax-britannica
which pax-britannica-data && man pax-britannica-data | cat | head -n 4 | grep -i pax-britannica-data
which pcsx2 && man pcsx2 | cat | head -n 4 | grep -i pcsx2
which pcsxr && man pcsxr | cat | head -n 4 | grep -i pcsxr
which peg-e && man peg-e | cat | head -n 4 | grep -i peg-e
which peg-solitaire && man peg-solitaire | cat | head -n 4 | grep -i peg-solitaire
which pegsolitaire && man pegsolitaire | cat | head -n 4 | grep -i pegsolitaire
which penguin-command  && man penguin-command  | cat | head -n 4 | grep -i penguin-command 
which pente && man pente | cat | head -n 4 | grep -i pente
which pentobi && man pentobi | cat | head -n 4 | grep -i pentobi
which performous && man performous | cat | head -n 4 | grep -i performous
which performous-tools && man performous-tools | cat | head -n 4 | grep -i performous-tools
which pescetti && man pescetti | cat | head -n 4 | grep -i pescetti
which petris && man petris | cat | head -n 4 | grep -i petris
which pgn-extract && man pgn-extract | cat | head -n 4 | grep -i pgn-extract
which phalanx && man phalanx | cat | head -n 4 | grep -i phalanx
which phlipple && man phlipple | cat | head -n 4 | grep -i phlipple
which phlipple-data && man phlipple-data | cat | head -n 4 | grep -i phlipple-data
which pianobooster && man pianobooster | cat | head -n 4 | grep -i pianobooster
which picmi && man picmi | cat | head -n 4 | grep -i picmi
which pinball && man pinball | cat | head -n 4 | grep -i pinball
which pinball-data && man pinball-data | cat | head -n 4 | grep -i pinball-data
which pinball-dev && man pinball-dev | cat | head -n 4 | grep -i pinball-dev
which pingus && man pingus | cat | head -n 4 | grep -i pingus
which pingus-data && man pingus-data | cat | head -n 4 | grep -i pingus-data
which pink-pony && man pink-pony | cat | head -n 4 | grep -i pink-pony
which pink-pony-data && man pink-pony-data | cat | head -n 4 | grep -i pink-pony-data
which pioneers && man pioneers | cat | head -n 4 | grep -i pioneers
which pioneers-console && man pioneers-console | cat | head -n 4 | grep -i pioneers-console
which pioneers-console-data && man pioneers-console-data | cat | head -n 4 | grep -i pioneers-console-data
which pioneers-data && man pioneers-data | cat | head -n 4 | grep -i pioneers-data
which pioneers-meta-server && man pioneers-meta-server | cat | head -n 4 | grep -i pioneers-meta-server
which pioneers-metaserver && man pioneers-metaserver | cat | head -n 4 | grep -i pioneers-metaserver
which pipenightdreams && man pipenightdreams | cat | head -n 4 | grep -i pipenightdreams
which pipenightdreams-data && man pipenightdreams-data | cat | head -n 4 | grep -i pipenightdreams-data
which pipewalker && man pipewalker | cat | head -n 4 | grep -i pipewalker
which pixbros && man pixbros | cat | head -n 4 | grep -i pixbros
which pixfrogger && man pixfrogger | cat | head -n 4 | grep -i pixfrogger
which plee-the-bear && man plee-the-bear | cat | head -n 4 | grep -i plee-the-bear
which plee-the-bear-data && man plee-the-bear-data | cat | head -n 4 | grep -i plee-the-bear-data
which pokerth && man pokerth | cat | head -n 4 | grep -i pokerth
which pokerth-data && man pokerth-data | cat | head -n 4 | grep -i pokerth-data
which pokerth-server && man pokerth-server | cat | head -n 4 | grep -i pokerth-server
which polygen && man polygen | cat | head -n 4 | grep -i polygen
which polygen-data && man polygen-data | cat | head -n 4 | grep -i polygen-data
which polyglot && man polyglot | cat | head -n 4 | grep -i polyglot
which pong2 && man pong2 | cat | head -n 4 | grep -i pong2
which powder && man powder | cat | head -n 4 | grep -i powder
which powermanga && man powermanga | cat | head -n 4 | grep -i powermanga
which powermanga-data && man powermanga-data | cat | head -n 4 | grep -i powermanga-data
which prboom-plus && man prboom-plus | cat | head -n 4 | grep -i prboom-plus
which prboom-plus-game-server && man prboom-plus-game-server | cat | head -n 4 | grep -i prboom-plus-game-server
which primrose && man primrose | cat | head -n 4 | grep -i primrose
which projectl && man projectl | cat | head -n 4 | grep -i projectl
which purity && man purity | cat | head -n 4 | grep -i purity
which purity-ng && man purity-ng | cat | head -n 4 | grep -i purity-ng
which purity-off && man purity-off | cat | head -n 4 | grep -i purity-off
which pybik && man pybik | cat | head -n 4 | grep -i pybik
which pybik-bin && man pybik-bin | cat | head -n 4 | grep -i pybik-bin
which pybridge && man pybridge | cat | head -n 4 | grep -i pybridge
which pybridge-common  && man pybridge-common  | cat | head -n 4 | grep -i pybridge-common 
which pybridge-server && man pybridge-server | cat | head -n 4 | grep -i pybridge-server
which pychess && man pychess | cat | head -n 4 | grep -i pychess
which pykaraoke && man pykaraoke | cat | head -n 4 | grep -i pykaraoke
which pykaraoke-bin && man pykaraoke-bin | cat | head -n 4 | grep -i pykaraoke-bin
which pynagram && manpynagram | cat | head -n 4  | grep -i pynagram
which pyracerz && man pyracerz | cat | head -n 4 | grep -i pyracerz
which pyscrabble && man pyscrabble | cat | head -n 4 | grep -i pyscrabble
which pyscrabble-common && man pyscrabble-common | cat | head -n 4 | grep -i pyscrabble-common
which pyscrabble-server && man pyscrabble-server | cat | head -n 4 | grep -i pyscrabble-server
which pysiogame && man pysiogame | cat | head -n 4 | grep -i pysiogame
which pysolfc && man pysolfc | cat | head -n 4 | grep -i pysolfc
which pysolfc-cardsets && man pysolfc-cardsets | cat | head -n 4 | grep -i pysolfc-cardsets
which pysycache && man pysycache | cat | head -n 4 | grep -i pysycache
which pysycache-buttons-beerabbit && man pysycache-buttons-beerabbit | cat | head -n 4 | grep -i pysycache-buttons-beerabbit
which pysycache-buttons-crapaud && man pysycache-buttons-crapaud | cat | head -n 4 | grep -i pysycache-buttons-crapaud
which pysycache-buttons-ice && man pysycache-buttons-ice | cat | head -n 4 | grep -i pysycache-buttons-ice
which pysycache-buttons-wolf && man pysycache-buttons-wolf | cat | head -n 4 | grep -i pysycache-buttons-wolf
which pysycache-click-dinosaurs  && man pysycache-click-dinosaurs  | cat | head -n 4 | grep -i pysycache-click-dinosaurs 
which pysycache-click-sea  && man pysycache-click-sea  | cat | head -n 4 | grep -i pysycache-click-sea 
which pysycache-dblclick-appleandpear && man pysycache-dblclick-appleandpear | cat | head -n 4 | grep -i pysycache-dblclick-appleandpear
which pysycache-dblclick-butterfly && man pysycache-dblclick-butterfly | cat | head -n 4 | grep -i pysycache-dblclick-butterfly
which pysycache-images && man pysycache-images | cat | head -n 4 | grep -i pysycache-images
which pysycache-move-animals && man pysycache-move-animals | cat | head -n 4 | grep -i pysycache-move-animals
which pysycache-move-food && man pysycache-move-food | cat | head -n 4 | grep -i pysycache-move-food
which pysycache-move-plants && man pysycache-move-plants | cat | head -n 4 | grep -i pysycache-move-plants
which pysycache-move-sky && man pysycache-move-sky | cat | head -n 4 | grep -i pysycache-move-sky
which pysycache-move-sports && man pysycache-move-sports | cat | head -n 4 | grep -i pysycache-move-sports
which pysycache-puzzle-cartoons && man pysycache-puzzle-cartoons | cat | head -n 4 | grep -i pysycache-puzzle-cartoons
which pysycache-puzzle-photos && man pysycache-puzzle-photos | cat | head -n 4 | grep -i pysycache-puzzle-photos
which pysycache-sounds && man pysycache-sounds | cat | head -n 4 | grep -i pysycache-sounds
which python-pykaraoke && man python-pykaraoke | cat | head -n 4 | grep -i python-pykaraoke
which python-renpy && man python-renpy | cat | head -n 4 | grep -i python-renpy
which qgo && man qgo | cat | head -n 4 | grep -i qgo
which qonk && man qonk | cat | head -n 4 | grep -i qonk
which qstat && man qstat | cat | head -n 4 | grep -i qstat
which qtads && man qtads | cat | head -n 4 | grep -i qtads
which quadrapassel && man quadrapassel | cat | head -n 4 | grep -i quadrapassel
which quake && man quake | cat | head -n 4 | grep -i quake
which quake-server && man quake-server | cat | head -n 4 | grep -i quake-server
which quake2 && man quake2 | cat | head -n 4 | grep -i quake2
which quake2-server && man quake2-server | cat | head -n 4 | grep -i quake2-server
which quake3 && man quake3 | cat | head -n 4 | grep -i quake3
which quake3-server && man quake3-server | cat | head -n 4 | grep -i quake3-server
which quake4 && man quake4 | cat | head -n 4 | grep -i quake4
which quake4-server && man quake4-server | cat | head -n 4 | grep -i quake4-server
which quakespasm && man quakespasm | cat | head -n 4 | grep -i quakespasm
which quarry && man quarry | cat | head -n 4 | grep -i quarry
which qxw && man qxw | cat | head -n 4 | grep -i qxw
which rafkill && man rafkill | cat | head -n 4 | grep -i rafkill
which rafkill-data && man rafkill-data | cat | head -n 4 | grep -i rafkill-data
which raincat && man raincat | cat | head -n 4 | grep -i raincat
which raincat-data && man raincat-data | cat | head -n 4 | grep -i raincat-data
which randtype && man randtype | cat | head -n 4 | grep -i randtype
which rbdoom3bfg && man rbdoom3bfg | cat | head -n 4 | grep -i rbdoom3bfg
which redeclipse && man redeclipse | cat | head -n 4 | grep -i redeclipse
which redeclipse-common && man redeclipse-common | cat | head -n 4 | grep -i redeclipse-common
which redeclipse-data && man redeclipse-data | cat | head -n 4 | grep -i redeclipse-data
which redeclipse-server && man redeclipse-server | cat | head -n 4 | grep -i redeclipse-server
which reminiscence && man reminiscence | cat | head -n 4 | grep -i reminiscence
which renpy && man renpy | cat | head -n 4 | grep -i renpy
which renpy-demo && man renpy-demo | cat | head -n 4 | grep -i renpy-demo
which renpy-thequestion && man renpy-thequestion | cat | head -n 4 | grep -i renpy-thequestion
which residualvm && man residualvm | cat | head -n 4 | grep -i residualvm
which residualvm-data && man residualvm-data | cat | head -n 4 | grep -i residualvm-data
which ri-li && man ri-li | cat | head -n 4 | grep -i ri-li
which ri-li-data && man ri-li-data | cat | head -n 4 | grep -i ri-li-data
which ricochet && man ricochet | cat | head -n 4 | grep -i ricochet
which rlvm && man rlvm | cat | head -n 4 | grep -i rlvm
which robocode && man robocode | cat | head -n 4 | grep -i robocode
which robotfindskitten && man robotfindskitten | cat | head -n 4 | grep -i robotfindskitten
which rockdodger && man rockdodger | cat | head -n 4 | grep -i rockdodger
which rocksndiamonds && man rocksndiamonds | cat | head -n 4 | grep -i rocksndiamonds
which rolldice && man rolldice | cat | head -n 4 | grep -i rolldice
which rott && man rott | cat | head -n 4 | grep -i rott
which rrootage && man rrootage | cat | head -n 4 | grep -i rrootage
which rrootage-data && man rrootage-data | cat | head -n 4 | grep -i rrootage-data
which rtcw && man rtcw | cat | head -n 4 | grep -i rtcw
which rtcw-common && man rtcw-common | cat | head -n 4 | grep -i rtcw-common
which rtcw-server && man rtcw-server | cat | head -n 4 | grep -i rtcw-server
which runescape && man runescape | cat | head -n 4 | grep -i runescape
which salliere && man salliere | cat | head -n 4 | grep -i salliere
which sandboxgamemaker && man sandboxgamemaker | cat | head -n 4 | grep -i sandboxgamemaker
which sauerbraten && man sauerbraten | cat | head -n 4 | grep -i sauerbraten
which sauerbraten-server && man sauerbraten-server | cat | head -n 4 | grep -i sauerbraten-server
which scid && man scid | cat | head -n 4 | grep -i scid
which scid-data && man scid-data | cat | head -n 4 | grep -i scid-data 
which scid-rating-data && man scid-rating-data | cat | head -n 4 | grep -i scid-rating-data
which scid-spell-data && man scid-spell-data | cat | head -n 4 | grep -i scid-spell-data
which scorched3d && man scorched3d | cat | head -n 4 | grep -i scorched3d
which scorched3d-data && man scorched3d-data | cat | head -n 4 | grep -i scorched3d-data
which scottfree && man scottfree | cat | head -n 4 | grep -i scottfree
which scummvm && man scummvm | cat | head -n 4 | grep -i scummvm
which scummvm-data && man scummvm-data | cat | head -n 4 | grep -i scummvm-data
which scummvm-tools && man scummvm-tools | cat | head -n 4 | grep -i scummvm-tools
which sdl-ball && man sdl-ball | cat | head -n 4 | grep -i sdl-ball
which sdl-ball-data && man sdl-ball-data | cat | head -n 4 | grep -i sdl-ball-data
which seahorse-adventures && man seahorse-adventures | cat | head -n 4 | grep -i seahorse-adventures
which searchandrescue && man searchandrescue | cat | head -n 4 | grep -i searchandrescue
which searchandrescue-common && man searchandrescue-common | cat | head -n 4 | grep -i searchandrescue-common
which searchandrescue-data && man searchandrescue-data | cat | head -n 4 | grep -i searchandrescue-data
which sgt-puzzles && man sgt-puzzles | cat | head -n 4 | grep -i sgt-puzzles
which shogivar && man shogivar | cat | head -n 4 | grep -i shogivar
which shogivar-data && man shogivar-data | cat | head -n 4 | grep -i shogivar-data
which simutrans && man simutrans | cat | head -n 4 | grep -i  simutrans
which simutrans-data && man simutrans-data | cat | head -n 4 | grep -i simutrans-data
which simutrans-makeobj && man simutrans-makeobj | cat | head -n 4 | grep -i simutrans-makeobj
which simutrans-pak128.britain && man simutrans-pak128.britain | cat | head -n 4 | grep -i simutrans-pak128.britain
which simutrans-pak64  && man simutrans-pak64  | cat | head -n 4 | grep -i simutrans-pak64 
which singularity && man singularity | cat | head -n 4 | grep -i singularity
which singularity-music && man singularity-music | cat | head -n 4 | grep -i singularity-music
which sjaakii && man sjaakii | cat | head -n 4 | grep -i sjaakii
which sjeng && man sjeng | cat | head -n 4 | grep -i sjeng
which sl && man sl | cat | head -n 4 | grep -i sl
which slashem && man slashem | cat | head -n 4 | grep -i slashem 
which slashem-common && man slashem-common | cat | head -n 4 | grep -i slashem-common
which slashem-gtk && man slashem-gtk | cat | head -n 4 | grep -i slashem-gtk
which slashem-sdl && man slashem-sdl | cat | head -n 4 | grep -i slashem-sdl
which slashem-x11 && man slashem-x11 | cat | head -n 4 | grep -i slashem-x11
which slimevolley && man slimevolley | cat | head -n 4 | grep -i slimevolley
which slimevolley-data && man slimevolley-data | cat | head -n 4 | grep -i slimevolley-data
which sludge-engine && man sludge-engine | cat | head -n 4 | grep -i sludge-engine
which sm && man sm | cat | head -n 4 | grep -i sm
which snake4 && man snake4 | cat | head -n 4 | grep -i snake4
which snowballz && man snowballz | cat | head -n 4 | grep -i snowballz
which solarwolf && man solarwolf | cat | head -n 4 | grep -i solarwolf
which sopwith && man sopwith | cat | head -n 4 | grep -i sopwith
which spacearyarya && man spacearyarya | cat | head -n 4 | grep -i spacearyarya
which spacezero && man spacezero | cat | head -n 4 | grep -i spacezero
which speedpad && man speedpad | cat | head -n 4 | grep -i speedpad
which spellcast && man spellcast | cat | head -n 4 | grep -i spellcast
which spout && man spout | cat | head -n 4 | grep -i spout
which spring && man spring | cat | head -n 4 | grep -i spring
which spring-common && man spring-common | cat | head -n 4 | grep -i spring-common
which spring-javaai && man spring-javaai | cat | head -n 4 | grep -i spring-javaai
which springlobby && man springlobby | cat | head -n 4 | grep -i springlobby
which starfighter && man starfighter | cat | head -n 4 | grep -i starfighter
which starfighter-data && man starfighter-data | cat | head -n 4 | grep -i starfighter-data
which starvoyager && man starvoyager | cat | head -n 4 | grep -i starvoyager
which starvoyager-data && man starvoyager-data | cat | head -n 4 | grep -i starvoyager-data
which stax && man stax | cat | head -n 4 | grep -i stax
which steam && man steam | cat | head -n 4 | grep -i steam
which steam-devices && man steam-devices | cat | head -n 4 | grep -i steam-devices
which steamcmd && man steamcmd | cat | head -n 4 | grep -i steamcmd
which stockfish && man stockfish | cat | head -n 4 | grep -i stockfish
which stormbaancoureur && man stormbaancoureur | cat | head -n 4 | grep -i stormbaancoureur
which stormbaancoureur-data && man stormbaancoureur-data | cat | head -n 4 | grep -i stormbaancoureur-data
which sudoku && man sudoku | cat | head -n 4 | grep -i sudoku
which supertransball2 && man supertransball2 | cat | head -n 4 | grep -i supertransball2
which supertransball2-data && man supertransball2-data | cat | head -n 4 | grep -i supertransball2-data
which supertux && man supertux | cat | head -n 4 | grep -i supertux
which supertux-data && man supertux-data | cat | head -n 4 | grep -i supertux-data
which supertuxkart && man supertuxkart | cat | head -n 4 | grep -i supertuxkart
which supertuxkart-data && man supertuxkart-data | cat | head -n 4 | grep -i supertuxkart-data
which swell-foop && man swell-foop | cat | head -n 4 | grep -i swell-foop
which tagua && man tagua | cat | head -n 4 | grep -i tagua
which tagua-data | cat | head -n 4 | grep -i tagua-data 
which tali && man tali | cat | head -n 4 | grep -i tali
which tanglet && man tanglet | cat | head -n 4 | grep -i tanglet
which tanglet-data && man tanglet-data | cat | head -n 4 | grep -i tanglet-data
which tatan && man tatan | cat | head -n 4 | grep -i tatan
which tdfsb && man tdfsb | cat | head -n 4 | grep -i tdfsb
which tecnoballz && man tecnoballz | cat | head -n 4 | grep -i tecnoballz
which tecnoballz-data && man tecnoballz-data | cat | head -n 4 | grep -i tecnoballz-data
which teeworlds && man teeworlds | cat | head -n 4 | grep -i teeworlds
which teeworlds-data && man teeworlds-data | cat | head -n 4 | grep -i teeworlds-data
which teeworlds-server && man teeworlds-server | cat | head -n 4 | grep -i teeworlds-server
which tenace && man tenace | cat | head -n 4 | grep -i tenace
which tenmado && man tenmado | cat | head -n 4 | grep -i tenmado 
which tennix && man tennix | cat | head -n 4 | grep -i tennix
which tetrinet-client && man tetrinet-client | cat | head -n 4 | grep -i tetrinet-client
which tetrinet-server && man tetrinet-server | cat | head -n 4 | grep -i tetrinet-server
which tetrinetx && man tetrinetx | cat | head -n 4 | grep -i tetrinetx
which tetzle && man tetzle | cat | head -n 4 | grep -i tetzle
which tf && man tf | cat | head -n 4 | grep -i tf
which tictactoe-ng && man tictactoe-ng | cat | head -n 4 | grep -i tictactoe-ng
which tint && man tint | cat | head -n 4 | grep -i tint
which tintin++ && man tintin++ | cat | head -n 4 | grep -i tintin++
which tinymux && man tinymux | cat | head -n 4 | grep -i tinymux
which titanion && man titanion | cat | head -n 4 | grep -i titanion
which titanion-data && man titanion-data | cat | head -n 4 | grep -i titanion-data
which toga2 && man toga2 | cat | head -n 4 | grep -i toga2
which tomatoes && man tomatoes | cat | head -n 4 | grep -i tomatoes
which tomatoes-data && man tomatoes-data | cat | head -n 4 | grep -i tomatoes-data
which tome && man tome | cat | head -n 4 | grep -i tome
which toppler && man toppler | cat | head -n 4 | grep -i toppler
which torcs && man torcs | cat | head -n 4 | grep -i torcs
which torcs-data && man torcs-data | cat | head -n 4 | grep -i torcs-data
which torcs-data-cars && man torcs-data-cars | cat | head -n 4 | grep -i torcs-data-cars
which torcs-data-tracks && man torcs-data-tracks | cat | head -n 4 | grep -i torcs-data-tracks
which torus-trooper && man torus-trooper | cat | head -n 4 | grep -i torus-trooper
which torus-trooper-data && man torus-trooper-data | cat | head -n 4 | grep -i torus-trooper-data
which tourney-manager  && man tourney-manager  | cat | head -n 4 | grep -i tourney-manager 
which transcend && man transcend | cat | head -n 4 | grep -i transcend
which trigger-rally && man trigger-rally | cat | head -n 4 | grep -i trigger-rally
which trigger-rally-data && man trigger-rally-data | cat | head -n 4 | grep -i trigger-rally-data
which triplane && man triplane | cat | head -n 4 | grep -i triplane
which triplea && man triplea | cat | head -n 4 | grep -i triplea
which trophy && man trophy | cat | head -n 4 | grep -i trophy
which trophy-data && man trophy-data | cat | head -n 4 | grep -i trophy-data
which tumiki-fighters && man tumiki-fighters | cat | head -n 4 | grep -i tumiki-fighters
which tumiki-fighters-data && man tumiki-fighters-data | cat | head -n 4 | grep -i tumiki-fighters-data
which tuxfootball && man tuxfootball | cat | head -n 4 | grep -i tuxfootball
which tuxmath && man tuxmath | cat | head -n 4 | grep -i tuxmath
which tuxmath-data && man tuxmath-data | cat | head -n 4 | grep -i tuxmath-data
which tuxpuck && man tuxpuck | cat | head -n 4 | grep -i tuxpuck
which tuxtype && man tuxtype | cat | head -n 4 | grep -i tuxtype
which tuxtype-data && man tuxtype-data | cat | head -n 4 | grep -i tuxtype-data
which tworld && man tworld | cat | head -n 4 | grep -i tworld
which tworld-data && man tworld-data | cat | head -n 4 | grep -i tworld-data
which typespeed && man typespeed | cat | head -n 4 | grep -i typespeed
which uci2wb && man uci2wb | cat | head -n 4 | grep -i uci2wb
which ufoai && man ufoai | cat | head -n 4 | grep -i ufoai
which ufoai-common && man ufoai-common | cat | head -n 4 | grep -i ufoai-common
which ufoai-data && man ufoai-data | cat | head -n 4 | grep -i ufoai-data
which ufoai-maps && man ufoai-maps | cat | head -n 4 | grep -i ufoai-maps
which ufoai-misc && man ufoai-misc | cat | head -n 4 | grep -i ufoai-misc
which ufoai-music && man ufoai-music | cat | head -n 4 | grep -i ufoai-music
which ufoai-server && man ufoai-server | cat | head -n 4 | grep -i ufoai-server
which ufoai-sound && man ufoai-sound | cat | head -n 4 | grep -i ufoai-sound
which ufoai-textures && man ufoai-textures | cat | head -n 4 | grep -i ufoai-textures
which uhexen2 && man uhexen2 | cat | head -n 4 | grep -i uhexen2
which uhexen2-common && man uhexen2-common | cat | head -n 4 | grep -i uhexen2-common
which uligo && man uligo | cat | head -n 4 | grep -i uligo
which unknown-horizons && man unknown-horizons | cat | head -n 4 | grep -i unknown-horizons
which uqm && man uqm | cat | head -n 4 | grep -i uqm
whivh uqm-content && man uqm-content | cat | head -n 4 | grep -i uqm-content
which uqm-music && man uqm-music | cat | head -n 4 | grep -i uqm-music
which uqm-russian && man uqm-russian | cat | head -n 4 | grep -i uqm-russian
which uqm-voice && man uqm-voice | cat | head -n 4 | grep -i uqm-voice
which val-and-rick && man val-and-rick | cat | head -n 4 | grep -i val-and-rick
which val-and-rick-data && man val-and-rick-data | cat | head -n 4 | grep -i val-and-rick-data
which vcmi && man vcmi | cat | head -n 4 | grep -i vcmi
which vectoroids && man vectoroids | cat | head -n 4 | grep -i vectoroids
which viruskiller && man viruskiller | cat | head -n 4 | grep -i viruskiller
which vodovod && man vodovod | cat | head -n 4 | grep -i vodovod
which vor && man vor | cat | head -n 4 | grep -i vor
which warmux && man warmux | cat | head -n 4 | grep -i warmux
which warmux-data && man warmux-data | cat | head -n 4 | grep -i warmux-data
which warmux-servers && man warmux-servers | cat | head -n 4 | grep -i warmux-servers
which warzone2100 && man warzone2100 | cat | head -n 4 | grep -i warzone2100
which warzone2100-data && man warzone2100-data | cat | head -n 4 | grep -i warzone2100-data
which warzone2100-music && man warzone2100-music | cat | head -n 4 | grep -i warzone2100-music
which werewolf && man werewolf | cat | head -n 4 | grep -i werewolf
which wesnoth && man wesnoth | cat | head -n 4 | grep -i wesnoth
which wesnoth-1.12 && man wesnoth-1.12 | cat | head -n 4 | grep -i wesnoth-1.12
which wesnoth-1.12-aoi && man wesnoth-1.12-aoi | cat | head -n 4 | grep -i wesnoth-1.12-aoi
which wesnoth-1.12-core && man wesnoth-1.12-core | cat | head -n 4 | grep -i wesnoth-1.12-core
which wesnoth-1.12-data && man wesnoth-1.12-data | cat | head -n 4 | grep -i wesnoth-1.12-data
which wesnoth-1.12-did && man wesnoth-1.12-did | cat | head -n 4 | grep -i wesnoth-1.12-did
which wesnoth-1.12-dm && man wesnoth-1.12-dm | cat | head -n 4 | grep -i wesnoth-1.12-dm
which wesnoth-1.12-dw && man wesnoth-1.12-dw | cat | head -n 4 | grep -i wesnoth-1.12-dw
which wesnoth-1.12-ei && man wesnoth-1.12-ei | cat | head -n 4 | grep -i wesnoth-1.12-ei
which wesnoth-1.12-httt && man wesnoth-1.12-httt | cat | head -n 4 | grep -i wesnoth-1.12-httt
which wesnoth-1.12-l && man wesnoth-1.12-l | cat | head -n 4 | grep -i wesnoth-1.12-l
which wesnoth-1.12-low && man wesnoth-1.12-low | cat | head -n 4 | grep -i wesnoth-1.12-low
which wesnoth-1.12-music && man wesnoth-1.12-music | cat | head -n 4 | grep -i wesnoth-1.12-music
which wesnoth-1.12-nr && man wesnoth-1.12-nr | cat | head -n 4 | grep -i wesnoth-1.12-nr
which wesnoth-1.12-server && man wesnoth-1.12-server | cat | head -n 4 | grep -i wesnoth-1.12-server
which wesnoth-1.12-sof && man wesnoth-1.12-sof | cat | head -n 4 | grep -i wesnoth-1.12-sof
which wesnoth-1.12-sotbe && man wesnoth-1.12-sotbe | cat | head -n 4 | grep -i wesnoth-1.12-sotbe
which wesnoth-1.12-thot && man wesnoth-1.12-thot | cat | head -n 4 | grep -i wesnoth-1.12-thot
which wesnoth-1.12-tools && man wesnoth-1.12-tools | cat | head -n 4 | grep -i wesnoth-1.12-tools
which wesnoth-1.12-trow && man wesnoth-1.12-trow | cat | head -n 4 | grep -i wesnoth-1.12-trow
which wesnoth-1.12-tsg && man wesnoth-1.12-tsg | cat | head -n 4 | grep -i wesnoth-1.12-tsg
which wesnoth-1.12-ttb && man wesnoth-1.12-ttb | cat | head -n 4 | grep -i wesnoth-1.12-ttb
which wesnoth-1.12-utbs && man wesnoth-1.12-utbs | cat | head -n 4 | grep -i wesnoth-1.12-utbs
which wesnoth-core && man wesnoth-core | cat | head -n 4 | grep -i wesnoth-core
which wesnoth-music && man wesnoth-music | cat | head -n 4 | grep -i wesnoth-music
which wfut && man wfut | cat | head -n 4 | grep -i wfut
which whichwayisup && man whichwayisup | cat | head -n 4 | grep -i whichwayisup
which widelands && man widelands | cat | head -n 4 | grep -i widelands
which widelands-data && man widelands-data | cat | head -n 4 | grep -i widelands-data
which wing && man wing | cat | head -n 4 | grep -i wing
which wing-data && man wing-data | cat | head -n 4 | grep -i wing-data
which wizznic && man wizznic | cat | head -n 4 | grep -i wizznic
which wizznic-data && man wizznic-data | cat | head -n 4 | grep -i wizznic-data
which wmpuzzle && man wmpuzzle | cat | head -n 4 | grep -i wmpuzzle
which wolf4sdl && man wolf4sdl | cat | head -n 4 | grep -i wolf4sdl
which wordplay && man wordplay | cat | head -n 4 | grep -i wordplay
which wordwarvi && man wordwarvi | cat | head -n 4 | grep -i wordwarvi
which wordwarvi-sound && man wordwarvi-sound | cat | head -n 4 | grep -i wordwarvi-sound
which xabacus && man xabacus | cat | head -n 4 | grep -i xabacus
which xball && man xball | cat | head -n 4 | grep -i xball
which xbill && man xbill | cat | head -n 4 | grep -i xbill
which xblast-tnt && man xblast-tnt | cat | head -n 4 | grep -i xblast-tnt
which xblast-tnt-images && man xblast-tnt-images | cat | head -n 4 | grep -i xblast-tnt-images
which xblast-tnt-levels && man xblast-tnt-levels | cat | head -n 4 | grep -i xblast-tnt-levels
which xblast-tnt-models && man xblast-tnt-models | cat | head -n 4 | grep -i xblast-tnt-models
which xblast-tnt-musics && man xblast-tnt-musics | cat | head -n 4 | grep -i xblast-tnt-musics
which xblast-tnt-sounds && man xblast-tnt-sounds | cat | head -n 4 | grep -i xblast-tnt-sounds
which xboard && man xboard | cat | head -n 4 | grep -i xboard
which xbomb && man xbomb | cat | head -n 4 | grep -i xbomb
which xbubble && man xbubble | cat | head -n 4 | grep -i xbubble
which xbubble-data && man xbubble-data | cat | head -n 4 | grep -i xbubble-data
which xchain && man xchain | cat | head -n 4 | grep -i xchain
which xcowsay && man xcowsay | cat | head -n 4 | grep -i xcowsay
which xdemineur && man xdemineur | cat | head -n 4 | grep -i xdemineur
which xdesktopwaves && man xdesktopwaves | cat | head -n 4 | grep -i xdesktopwaves
which xfireworks && man xfireworks | cat | head -n 4 | grep -i xfireworks
which xfishtank && man xfishtank | cat | head -n 4 | grep -i xfishtank
which xflip && man xflip | cat | head -n 4 | grep -i xflip
which xfrisk && man xfrisk | cat | head -n 4 | grep -i xfrisk
which xgalaga++ && man xgalaga++ | cat | head -n 4 | grep -i xgalaga++
which xgammon && man xgammon | cat | head -n 4 | grep -i xgammon
which xinv3d && man xinv3d | cat | head -n 4 | grep -i xinv3d
which xjig && man xjig | cat | head -n 4 | grep -i xjig
which xjokes && man xjokes | cat | head -n 4 | grep -i xjokes
which xjump && man xjump | cat | head -n 4 | grep -i xjump
which xletters && man xletters | cat | head -n 4 | grep -i xletters
which xmabacus && man xmabacus | cat | head -n 4 | grep -i xmabacus
which xmahjongg && man xmahjongg | cat | head -n 4 | grep -i xmahjongg
which xmille && man xmille | cat | head -n 4 | grep -i xmille
which xmoto && man xmoto | cat | head -n 4 | grep -i xmoto
which xmoto-data && man xmoto-data | cat | head -n 4 | grep -i xmoto-data
which xmountains && man xmountains | cat | head -n 4 | grep -i xmountains
which xmpuzzles && man xmpuzzles | cat | head -n 4 | grep -i xmpuzzles
which xonix && man xonix | cat | head -n 4 | grep -i xonix
which xpat2 && man xpat2 | cat | head -n 4 | grep -i xpat2
which xpenguins && man xpenguins | cat | head -n 4 | grep -i xpenguins
which xphoon && man xphoon | cat | head -n 4 | grep -i xphoon
which xpilot-extra && man xpilot-extra | cat | head -n 4 | grep -i xpilot-extra
which xpilot-ng && man xpilot-ng | cat | head -n 4 | grep -i xpilot-ng
which xpilot-ng-client-sdl && man xpilot-ng-client-sdl | cat | head -n 4 | grep -i xpilot-ng-client-sdl
which xpilot-ng-client-x11 && man xpilot-ng-client-x11 | cat | head -n 4 | grep -i xpilot-ng-client-x11
which xpilot-ng-common && man xpilot-ng-common | cat | head -n 4 | grep -i xpilot-ng-common
which xpilot-ng-server && man xpilot-ng-server | cat | head -n 4 | grep -i xpilot-ng-server
which xpilot-ng-utils && man xpilot-ng-utils | cat | head -n 4 | grep -i xpilot-ng-utils
which xpuzzles && man xpuzzles | cat | head -n 4 | grep -i xpuzzles
which xqf && man xqf | cat | head -n 4  | grep -i xqf
which xracer && man xracer | cat | head -n 4 | grep -i xracer
which xracer-tools && man xracer-tools | cat | head -n 4 | grep -i xracer-tools
which xscavenger && man xscavenger | cat | head -n 4 | grep -i xscavenger
which xscorch && man xscorch | cat | head -n 4 | grep -i xscorch
which xscreensaver-screensaver-dizzy && man xscreensaver-screensaver-dizzy | cat | head -n 4 | grep -i xscreensaver-screensaver-dizzy
which xshisen && man xshisen | cat | head -n 4 | grep -i xshisen
which xshogi && man xshogi | cat | head -n 4 | grep -i xshogi
which xskat && man xskat | cat | head -n 4 | grep -i xskat
which xsnow && man xsnow | cat | head -n 4 | grep -i xsnow
which xsok && man xsok | cat | head -n 4 | grep -i xsok
which xsol && man xsol | cat | head -n 4 | grep -i xsol
which xsoldier && man xsoldier | cat | head -n 4 | grep -i xsoldier
which xsystem35 && man xsystem35 | cat | head -n 4 | grep -i xsystem35
which xteddy && man xteddy | cat | head -n 4 | grep -i xteddy
which xtron && man xtron | cat | head -n 4 | grep -i xtron
which xvier && man xvier | cat | head -n 4 | grep -i xvier
which xwelltris && man xwelltris | cat | head -n 4 | grep -i xwelltris
which xword && man xword | cat | head -n 4 | grep -i xword
which xzip && man xzip | cat | head -n 4 | grep -i xzip
which yahtzeesharp && man yahtzeesharp | cat | head -n 4 | grep -i yahtzeesharp
which yamagi-quake2 && man yamagi-quake2 | cat | head -n 4 | grep -i yamagi-quake2
which yamagi-quake2-core && man yamagi-quake2-core | cat | head -n 4 | grep -i yamagi-quake2-core
which zangband && man zangband | cat | head -n 4 | grep -i zangband
which zatacka && man zatacka | cat | head -n 4 | grep -i zatacka
which zaz && man zaz | cat | head -n 4 | grep -i zaz
which zaz-data && man zaz-data | cat | head -n 4 | grep -i zaz-data
which zec && man zec | cat | head -n 4 | grep -i zec
which zivot && man zivot | cat | head -n 4 | grep -i zivot
which zoom-player && man zoom-player | cat | head -n 4 | grep -i zoom-player
echo "-----------------------------------|"