#!/bin/sh
date=$(date -u)
if [ $(/usr/bin/id -u) -ne 0 ]; then
    echo "You must be root. This instance will be logged."
    echo "[FAIL] $USER attempted to run the search on $date." | sudo tee -a /bin/lib/sh/MK3S/logs/MK3S.log
    exit
fi
echo "---------------Games----------------|"
which 0ad && man 0ad | cat | head -n 4 | grep -i 0ad
which 0ad-data && man 0ad-data | cat | head -n 4 | grep -i 0ad-data
which 0ad-dada-common && man 0ad-data-common | cat | head -n 4 | grep -i 0ad-data-common
which 2048-at && man 2048-at | cat | head -n 4 | grep -i 2048-at
which 3dchess && man 3dchess | cat | head -n 4 | grep -i 3dchess
which 4digits && man 4digits | cat | head -n 4 | grep -i 4digits
which 7kaa && man 7kaa | cat | head -n 4 | grep -i 7kaa
which 7kaa-data && man 7kaa-data | cat | head -n 4 | grep -i 7kaa-data
which a7xpg && man a7xpg | cat | head -n 4 | grep -i a7xpg
which a7xpg-data && man a7xpg-data | cat | head -n 4 | grep -i a7xpg-data
which aajm && man aajm | cat | head -n 4 | grep -i aajm
which abe && man abe | cat | head -n 4 | grep -i abe
which abe-data && man abe-data | cat | head -n 4 | grep -i abe-data
which ace-of-penguins && man ace-of-penguins | cat | head -n 4 | grep -i ace-of-penguins
which acm && man acm | cat | head -n 4 | grep -i acm
which adanaxisgpl && man adanaxisgpl | cat | head -n 4 | grep -i adanaxisgpl
which adanaxisgpl-data && man adanaxisgpl-data | cat | head -n 4 | grep -i adanaxisgpl-data
which adonthell && man adonthell | cat | head -n 4 | grep -i adonthell
which adonthell-data && man adonthell-data  | cat | head -n 4 | grep -i adonthell-data 
which airstrike && man airstrike | cat | head -n -4 | grep -i airstrike
which airstrike-common && man airstrike-common | cat | head -n 4 | grep -i airstrike-common
which aisleriot && man aisleriot | cat | head -n 4 | grep -i aisleriot
which alex4 && man alex4 | cat | head -n 4 | grep -i alex4
which alex4-data && man alex4-data | cat | head -n 4 | grep -i alex4-data
which alien-arena && man alien-arena |cat | hean -n -4 | grep -i alien-arena
which alien-arena-data && man alien-arena-data | cat | head -n 4 | grep -i alien-arena-data
which alien-arena-server && man alien-arena-server | cat | head -n 4 | grep -i alien-arena-server
which alienblaster && man alienblaster | cat | head -n 4 | grep -i alienblaster
which alienblaster-data && man alienblaster-data | cat | head -n 4 | grep -i alienblaster-data
which amoebax && man amoebax | cat | head -n 4 | grep -i amoebax
which amoebax-data && man amoebax-data | cat | head -n 4 | grep -i amoebax-data
which amphetamine && man amphetamine | cat | head -n 4 | grep -i amphetamine
which amphetamine-data  && man amphetamine-data  | cat | head -n 4 | grep -i amphetamine-data 
which an && man an | cat | head -n 4 | grep -i an
which angband && man angband | cat | head -n 4 | grep -i angband
which angband-data && man angband-data | cat | head -n 4 | grep -i angband-data
which angrydd && man angrydd | cat | head -n 4 | grep -i angrydd
which animals && man animals | cat | head -n 4 | grep -i animals
which antigravitaattori && man antigravitaattori | cat | head -n 4 | grep -i antigravitaattori
which ardentryst && man ardentryst | cat | head -n 4 | grep -i ardentryst
which armagetronad && man armagetronad | cat | hean -n 4 | grep -i armagetronad
which armagetronad-common && man armagetronad-common | cat | head -n 4 | grep -i armagetronad-common
which armagetronad-dedicated && man armagetronad-dedicated | cat | head -n 4 | grep -i armagetronad-dedicated
which asc && man asc | cat | head -n 4 | grep -i asc
which asc-data && man asc-data | cat | head -n 4 | grep -i asc-data
which asc-music && man asc-music | cat | head -n 4 | grep -i asc-music
which asciijump && man asciijump | cat | head -n 4 | grep -i asciijump
which assaultcube && man assaultcube | cat | head -n 4 | grep -i assaultcube
which assaultcube-data && man assaultcube-data | cat | head -n 4 | grep -i assaultcube-data
which astromenace && man astromenace | cat | head -n 4 | grep -i astromenace
which astromenace-data-src && man astromenace-data-src | cat | head -n 4 | grep -i astromenace-data-src
which asylum && man asylum | cat | head -n 4 | grep -i asylum
which asylum-data && man asylum-data | cat | head -n 4 | grep -i asylum-data
which atanks && man atanks | cat | head -n 4 | grep -i atanks
which atanks-data && man atanks-data | cat | head -n 4 | grep -i atanks-data
which atom4 && man atom4 | cat | head -n 4 | grep -i atom4
which atomix && man atomix | cat | head -n 4 | grep -i atomix
which atomix-data && man atomix-data | cat | head -n 4 | grep -i atomix-data
which attal-themes-medieval && man attal-themes-medieval | cat | head -n 4 | grep -i attal-themes-medieval
which auralquiz && man auralquiz | cat | head -n 4 | grep -i auralquiz
which balder2d && man balder2d | cat | head -n 4 | grep -i balder2d
which balder2d-data && man balder2d-data | cat | head -n 4 | grep -i balder2d-data
which ballerburg && man ballerburg | cat | head -n 4 | grep -i ballerburg
which ballz && man ballz | cat | head -n 4 | grep -i ballz
which ballz-data && man ballz-data | cat | head -n 4 | grep -i ballz-data
which bambam && man bambam | cat | head -n 4 | grep -i bambam
which barrage && man barrage | cat | head -n 4 | grep -i barrage
which bastet && man bastet | cat | head -n 4 | grep -i bastet
which bb && man bb | cat | head -n 4 | grep -i bb
which beneath-a-steel-sky && man beneath-a-steel-sky | cat | head -n 4 | grep -i beneath-a-steel-sky
which berusky && man berusky | cat | head -n 4 | grep -i berusky
which berusky-data && man berusky-data | cat | head -n 4 | grep -i berusky-data
which berusky2 && man berusky2 | cat | head -n 4 | grep -i berusky2
which berusky2-data && man berusky2-data | cat | head -n 4 | grep -i berusky2-data
which between && man between | cat | head -n 4 | grep -i between
which billard-gl && man billard-gl  | cat | head -n 4 | grep -i billard-gl 
which billard-gl-data && man billard-gl-data | cat | head -n 4 | grep -i billard-gl-data
which biloba && man biloba | cat | head -n 4 | grep -i biloba
which biloba-data && man biloba-data | cat | head -n 4 | grep -i biloba-data
which biniax2 && man biniax2 | cat | head -n 4 | grep -i biniax2
which biniax2-data && man biniax2-data | cat | head -n 4 | grep -i biniax2-data
which black-box && man black-box | cat | head -n 4 | grep -i black-box
which blinken && man blinken | cat | head -n 4 | grep -i blinken 
which blobandconquer && man blobandconquer | cat | head -n 4 | grep -i blobandconquer
which blobandconquer-data && man blobandconquer-data | cat | head -n 4 | grep -i blobandconquer-data
which blobby && man blobby | cat | head -n 4 | grep -i blobby
which blobby-data && man blobby-data | cat | head -n 4 | grep -i blobby-data
which blobby-server && man blobby-server | cat | head -n 4 | grep -i blobby-server
which bloboats && man bloboats | cat | head -n 4 | grep -i bloboats
which blobwars && man blobwars | cat | head -n 4 | grep -i blobwars
which blobwars-data && man blobwars-data | cat | head -n 4 |  grep -i blobwars-data
which blockattack && man blockattack | cat | head -n 4 | grep -i blockattack
which blockout2 && man blockout2 | cat | head -n 4 | grep -i blockout2
which 3D-tetris && man 3D-tetris | cat | head -n 4 | grep -i 3D-tetris 
which Tetris\ like\ game && man Tetris\ like\ game | cat | head -n 4 | grep -i Tetris\ like\ game
which Tetris-like-game && man Tetris-like-game | cat | head -n 4 | grep -i Tetris-like-game
which blocks-of-the-undead && man blocks-of-the-undead | cat | head -n 4 | grep -i blocks-of-the-undead
which blocks-of-the-undead-data && man blocks-of-the-undead-data | cat | head -n 4 | grep -i blocks-of-the-undead-data
which bombardier && man bombardier | cat | head -n 4 | grep -i bombardier
which bomber && man bomber | cat | head -n 4 | grep -i bomber
which bomberclone && man bomberclone | cat | head -n 4 | grep -i bomberclone
which bomberclone-data && man bomberclone-data | cat | head -n 4 | grep -i bomberclone-data
which boswars && man boswars | cat | head -n 4 | grep -i boswars
which boswars-data  && man boswars-data  | cat | head -n 4 | grep -i boswars-data 
which bouncy && man bouncy | cat | head -n 4 | grep -i bouncy
which bovo && man bovo | cat | head -n 4 | grep -i bovo
which brainparty && man brainparty | cat | head -n 4 | grep -i brainparty
which brainparty-data && man brainparty-data | cat | head -n 4 | grep -i brainparty-data
which briquolo && man briquolo | cat | head -n 4 | grep -i briquolo
which briquolo-data && man briquolo-data | cat | head -n 4 | grep i briquolo-data
which brutalchess && man brutalchess | cat | head -n 4 | grep -i brutalchess
which bsdgames && man bsdgames | cat | head -n 4 | grep -i bsdgames
which bsdgames-nonfree && man bsdgames-nonfree | cat | head -n 4 | grep -i bsdgames-nonfree
which btanks && man btanks | cat | head -n 4 | grep -i btanks
which btanks-data && man btanks-data | cat | head -n 4 | grep -i btanks-data
which bubbros && man bubbros | cat | head -n 4 | grep -i bubbros
which bucklespring && man bucklespring | cat | head -n 4 | grep -i bucklespring
which bucklespring-data && man bucklespring-data | cat | head -n 4 | grep -i bucklespring-data
which bugsquish && man bugsquish | cat | head -n 4 | grep -i bugsquish
which bumprace && man bumprace | cat | head -n 4 | grep -i bumprace
which bumprace-data && man bumprace-data | cat | head -n 4 | grep -i bumprace-data
which burgerspace && man burgerspace | cat | head -n 4 | grep -i burgerspace
which bygfoot && man bygfoot | cat | head -n 4 | grep -i bygfoot
which bygfoot-data && man bygfoot-data | cat | head -n 4 | grep -i bygfoot-data
which bzflag && man bzflag | cat | head -n 4 | grep -i bzflag
which bzflag-client && man bzflag-client | cat | head -n 4 | grep -i bzflag-client
which bzflag-data && man bzflag-data | cat | head -n 4 | grep -i bzflag-data
which bzflag-server && man bzflag-server | cat | head -n 4 | grep -i bzflag-server
which cappuccino && man cappuccino | cat | head -n 4 | grep -i cappuccino
which caveexpress && man caveexpress | cat | head -n 4 | grep -i caveexpress
which caveexpress-data && man caveexpress-data | cat | head -n 4 | grep -i caveexpress-data
which cavepacker && man cavepacker | cat | head -n 4 | grep -i cavepacker
which cavepacker-data && man cavepacker-data | cat | head -n 4 | grep -i cavepacker-data
which cavezofphear && man cavezofphear | cat | head -n 4 | grep -i cavezofphear
which ceferino && man ceferino | cat | head -n 4 | grep -i ceferino
which ceferino-data && man ceferino-data | cat | head -n 4 | grep -i ceferino-data
which cgoban && man cgoban | cat | head -n 4 | grep -i cgoban
which chessx && man chessx | cat | head -n 4 | grep -i chessx
which childsplay && man childsplay | cat | head -n 4 | grep -i childsplay
which childsplay-alphabet-sounds-bg && man childsplay-alphabet-sounds-bg | cat | head -n 4 | grep -i childsplay-alphabet-sounds-bg
which childsplay-alphabet-sounds-el && man childsplay-alphabet-sounds-el | cat | head -n 4 | grep -i childsplay-alphabet-sounds-el
which childsplay-alphabet-sounds-en-gb && man childsplay-alphabet-sounds-en-gb | cat | head -n 4 | grep -i childsplay-alphabet-sounds-en-gb
which childsplay-alphabet-sounds-nb && man childsplay-alphabet-sounds-nb | cat | head -n 4 | grep -i childsplay-alphabet-sounds-nb
which childsplay-alphabet-sounds-ro && man childsplay-alphabet-sounds-ro | cat | head -n 4 | grep -i childsplay-alphabet-sounds-ro
which childsplay-alphabet-sounds-sl && man childsplay-alphabet-sounds-sl | cat | head -n 4 | grep -i childsplay-alphabet-sounds-sl
which chipw && man chipw | cat | head -n 4 | grep -i chipw
which chocolate-common && man chocolate-common | cat | head -n 4 | grep -i chocolate-common
which chocolate-doom && man chocolate-doom | cat | head -n 4 | grep -i chocolate-doom
which chromium-bsu && man chromium-bsu | cat | head -n 4 | grep -i chromium-bsu
which fhromium-bsu-data && man fhromium-bsu-data | cat | head -n 4 | grep -i fhromium-bsu-data
which circuslinux && man circuslinux | cat | head -n 4 | grep -i circuslinux
which circuslinux-data && man circuslinux-data | cat | head -n 4 | grep -i circuslinux-data
which colobot && man colobot | cat | head -n 4 | grep -i colobot
which colobot-common && man colobot-common | cat | head -n 4 | grep -i colobot-common
which colobot-common-sounds && man colobot-common-sounds | cat | head -n 4 | grep -i colobot-common-sounds
which colobot-common-textures && man colobot-common-textures | cat | head -n 4 | grep -i  colobot-common-textures
which colorcode && man colorcode | cat | head -n 4 | grep -i colorcode
which colossal-cave-adventure && man colossal-cave-adventure | cat | head -n 4 | grep -i colossal-cave-adventure
which connectagram && man connectagram | cat | head -n 4 | grep -i connectagram
which connectagram-data && man connectagram-data | cat | head -n 4 | grep -i connectagram-data
which cookietool && man cookietool | cat | head -n 4 | grep -i cookietool
which corsix-th && man corsix-th | cat | head -n 4 | grep -i corsix-th
which corsix-th-data && man corsix-th-data | cat | head -n 4 | grep -i corsix-th-data
which cowsay && man cowsay | cat | head -n 4 | grep -i cowsay
which cowsay-off && man cowsay-off | cat | head -n 4 | grep -i cowsay-off
which crack-attack && man crack-attack | cat | head -n 4 | grep -i crack-attack
which crafty && man crafty | cat | head -n 4 | grep -i crafty
which crafty-bitmaps && man crafty-bitmaps | cat | head -n 4 | grep -i crafty-bitmaps
which crafty-books-medium && man crafty-books-medium | cat | head -n 4 | grep -i crafty-books-medium
which crafty-books-medtosmall && man crafty-books-medtosmall | cat | head -n 4 | grep -i crafty-books-medtosmall
which crafty-books-small && man crafty-books-small | cat | head -n 4 | grep -i crafty-books-small
which crawl && man crawl | cat | head -n 4 | grep -i crawl
which crawl-common && man crawl-common | cat | head -n 4 | grep -i crawl-common
which crawl-tiles && man crawl-tiles | cat | head -n 4 | grep -i crawl-tiles
which crawl-tiles-data && man crawl-tiles-data | cat | head -n 4 | grep -i crawl-tiles-data
which crimson && man crimson | cat | head -n 4 | grep -i crimson
which criticalmass && man criticalmass | cat | head -n 4 | grep -i criticalmass
which criticalmass-data && man criticalmass-data | cat | head -n 4 | grep -i criticalmass-data
which crossfire-client && man crossfire-client | cat | head -n 4 | grep -i crossfire-client
which crossfire-client-images && man crossfire-client-images | cat | head -n 4 | grep -i crossfire-client-images
which crossfire-client-sounds && man crossfire-client-sounds | cat | head -n 4 | grep -i crossfire-client-sounds
which crossfire-common && man crossfire-common | cat | head -n 4 | grep -i crossfire-common
which crossfire-maps && man crossfire-maps | cat | head -n 4 | grep -i crossfire-maps
which crossfire-maps-small && man crossfire-maps-small | cat | head -n 4 | grep -i crossfire-maps-small
which crossfire-server && man crossfire-server | cat | head -n 4 | grep -i crossfire-server
which crrcsim && man crrcsim | cat | head -n 4 | grep -i crrcsim
which crrcsim-data && man crrcsim-data | cat | head -n 4 | grep -i crrcsim-data
which csmash && man csmash | cat | head -n 4 | grep -i csmash
which csmash-data && man csmash-data | cat | head -n 4 | grep -i csmash-data
which csmash-demosong && man csmash-demosong | cat | head -n 4 | grep -i csmash-demosong
which cube2 && man cube2 | cat | head -n 4 | grep -i cube2
which cube2-data && man cube2-data | cat | head -n 4 | grep -i cube2-data
which cube2-server && man cube2-server | cat | head -n 4 | grep -i cube2-server
which cultivation && man cultivation | cat | head -n 4 | grep -i cultivation
which curseofwar && man curseofwar | cat | head -n 4 | grep -i curseofwar
which cutemaze && man cutemaze | cat | head -n 4 | grep -i cutemaze
which cuyo && man cuyo | cat | head -n 4 | grep -i cuyo
which cuyo-data && man cuyo-data | cat | head -n 4 | grep -i cuyo-data
which cytadela && man cytadela | cat | head -n 4 | grep -i cytadela
which cytadela-data && man cytadela-data | cat | head -n 4 | grep -i cytadela-data
which d1x-rebirth && man d1x-rebirth | cat | head -n 4 | grep -i d1x-rebirth
which d2x-rebirth && man d2x-rebirth | cat | head -n 4 | grep -i d2x-rebirth
which dangen && man dangen | cat | head -n 4 | grep -i dangen
which darkplaces && man darkplaces | cat | head -n 4 | grep -i darkplaces
which darkplaces-server && man darkplaces-server | cat | head -n 4 | grep -i darkplaces-server
which dds && man dds | cat | head -n 4 | grep -i dds
which deal && man deal | cat | head -n 4 | grep -i deal
which dealer && man dealer | cat | head -n 4 | grep -i dealer
which defendguin && man defendguin | cat | head -n 4 | grep -i defendguin
which defendguin-data && man defendguin-data | cat | head -n 4 | grep -i defendguin-data
which desmume && man desmume | cat | head -n 4 | grep -i desmume
which deutex && man deutex | cat | head -n 4 | grep -i deutex
which dhewm3 && man dhewm3 | cat | head -n 4 | grep -i dhewm3
which dhewm3-d3xp && man dhewm3-d3xp | cat | head -n 4 | grep -i dhewm3-d3xp
which dhewm3-doom3 && man dhewm3-doom3 | cat | head -n 4 | grep -i dhewm3-doom3
which dizzy && man dizzy | cat | head -n 4 | grep -i dizzy
which dodgindiamond2 && man dodgindiamond2 | cat | head -n 4 | grep -i dodgindiamond2
which dolphin-emu && man dolphin-emu | cat | head -n 4 | grep -i dolphin-emu
which dolphin-emu-data && man dolphin-emu-data | cat | head -n 4 | grep -i dolphin-emu-data
which doom-wad-shareware && man doom-wad-shareware | cat | head -n 4 | grep -i doom-wad-shareware
which dopewars && man dopewars | cat | head -n 4 | grep -i dopewars
which dopewars-data  && man dopewars-data  | cat | head -n 4 | grep -i dopewars-data 
which dossizola && man dossizola | cat | head -n 4 | grep -i dossizola
which dossizola-data && man dossizola-data | cat | head -n 4 | grep -i dossizola-data
which drascula && man drascula | cat | head -n 4 | grep -i drascula
which drascula-french  && man drascula-french  | cat | head -n 4 | grep -i drascula-french 
which drascula-german && man drascula-german | cat | head -n 4 | grep -i drascula-german
which drascula-italian  && man drascula-italian  | cat | head -n 4 | grep -i drascula-italian 
which drascula-music && man drascula-music | cat | head -n 4 | grep -i drascula-music
which drascula-spanish && man drascula-spanish | cat | head -n 4 | grep -i drascula-spanish
which dreamchess && man dreamchess | cat | head -n 4 | grep -i dreamchess
which dreamchess-data && man dreamchess-data | cat | head -n 4 | grep -i dreamchess-data
which dvorak7min && man dvorak7min | cat | head -n 4 | grep -i dvorak7min
which eboard && man eboard | cat | head -n 4 | grep -i eboard
which eboard-extras-pack1 && man eboard-extras-pack1 | cat | head -n 4 | grep -i eboard-extras-pack1
which efp && man efp | cat | head -n 4 | grep -i efp
which einstein && man einstein | cat | head -n 4 | grep -i einstein
which eleeye && man eleeye | cat | head -n 4 | grep -i eleeye
which ember && man ember| cat | head -n 4 | grep -i ember
which ember-media && ember-media | cat | head -n 4 | grep -i ember-media
which empire && man empire | cat | head -n 4 | grep -i empire
which empire-hub && man empire-hub | cat | head -n 4 | grep -i empire-hub
which empire-lafe && man empire-lafe | cat | head -n 4 | grep -i empire-lafe
which endless-sky && man endless-sky | cat | head -n 4 | grep -i endless-sky
which endless-sky-data && man endless-sky-data | cat | head -n 4 | grep -i endless-sky-data
which endless-sky-high-dpi && man endless-sky-high-dpi | cat | head -n 4 | grep -i endless-sky-high-dpi
which enemylines3 && man enemylines3 | cat | head -n 4 | grep -i enemylines3
which enemylines7 && man enemylines7 | cat | head -n 4 | grep -i enemylines7
which enigma && man enigma | cat | head -n 4 | grep -i enigma
which enigma-data && man enigma-data | cat | head -n 4 | grep -i enigma-data
which epiphany && man epiphany | cat | head -n 4 | grep -i epiphany
which epiphany-data && man epiphany-data | cat | head -n 4 | grep -i epiphany-data
which etoys && man etoys | cat | head -n 4 | grep -i etoys
which etqw && man etqw | cat | head -n 4 | grep -i etqw
which etqw-server  && man etqw-server  | cat | head -n 4 | grep -i etqw-server 
which etw && man etw | cat | head -n 4 | grep -i etw
which etw-data && man etw-data | cat | head -n 4 | grep -i etw-data
which excellent-bifurcation && man excellent-bifurcation | cat | head -n 4 | grep -i excellent-bifurcation
which extremetuxracer && man extremetuxracer | cat | head -n 4 | grep -i extremetuxracer
which extremetuxracer-data && man extremetuxracer-data | cat | head -n 4 | grep -i extremetuxracer-data
which exult && man exult | cat | head -n 4 | grep -i exult
which exult-studio && man exult-studio | cat | head -n 4 | grep -i exult-studio
which ezquake && man ezquake | cat | head -n 4 | grep -i ezquake
which fairymax && man fairymax | cat | head -n 4 | grep -i fairymax
which fb-music-high && man fb-music-high | cat | head -n 4 | grep -i fb-music-high
which fceux && man fceux | cat | head -n 4 | grep -i fceux
which ffrenzy && man ffrenzy | cat | head -n 4 | grep -i ffrenzy
which fgo && man fgo | cat | head -n 4 | grep -i fgo
which fheroes2-pkg && man fheroes2-pkg | cat | head -n 4 | grep -i fheroes2-pkg
which filler && man filler | cat | head -n 4 | grep -i filler
which fillets-ng && man fillets-ng | cat | head -n 4 | grep -i fillets-ng
which fillets-ng-data && man fillets-ng-data | cat | head -n 4 | grep -i fillets-ng-data
which fillets-ng-data-cs && man fillets-ng-data-cs | cat | head -n 4 | grep -i fillets-ng-data-cs
which fillets-ng-data-nl && man fillets-ng-data-nl | cat | head -n 4 | grep -i fillets-ng-data-nl
which filters && man filters | cat | head -n 4 | grep -i filters
which five-or-more  && man five-or-more  | cat | head -n 4 | grep -i five-or-more 
which fizmo-common && man fizmo-common | cat | head -n 4 | grep -i fizmo-common
which fizmo-console && man fizmo-console | cat | head -n 4 | grep -i fizmo-console
which fizmo-ncursesw && man fizmo-ncursesw | cat | head-n 4 | grep -i fizmo-ncursesw
which flare && man flare | cat | head -n 4 | grep -i flare
which flare-data && man flare-data | cat | head -n 4 | grep -i flare-data
which flare-engine && man flare-engine | cat | head -n 4 | grep -i flare-engine
which flare-game && man flare-game | cat | head -n 4 | grep -i flare-game
which flight-of-the-amazon-queen && man flight-of-the-amazon-queen | cat | head -n 4 | grep -i flight-of-the-amazon-queen
which flightgear && man flightgear | cat | head -n 4 | grep -i flightgear
which flightgear-data-ai && man flightgear-data-ai | cat | head -n 4 | grep -i flightgear-data-ai
which flightgear-data-all && manflightgear-data-all | cat | head -n 4 | grep -i flightgear-data-all
which flightgear-data-base && man flightgear-data-base | cat | head -n 4 | grep -i flightgear-data-base
which flightgear-data-models && man flightgear-data-models | cat | head -n 4 | grep -i flightgear-data-models
which flightgear-phi  && man flightgear-phi  | cat | head -n 4 | grep -i flightgear-phi 
which flobopuyo &&  man flobopuyo | cat | head -n 4 | grep -i flobopuyo
which fltk1.1-games && man fltk1.1-games | cat | head -n 4 | grep -i fltk1.1-games
which fltk1.3-games && man fltk1.3-games | cat | head -n 4 | grep -i fltk1.3-games
which fofix && man fofix | cat | head -n 4 | grep -i fofix
which foobillardplus && man foobillardplus | cat | head -n 4 | grep -i foobillardplus
which foobillardplus-data && man foobillardplus-data | cat | head -n 4 | grep -i foobillardplus-data

# NOT COMPLETE
